
var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign,ba=aa({},h),ca=[],da="./this.program",ea=(a,b)=>{throw b;},l="";"undefined"!==typeof document&&document.currentScript&&(l=document.currentScript.src);l=0!==l.indexOf("blob:")?l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var fa=h.print||console.log.bind(console),m=h.printErr||console.warn.bind(console);aa(h,ba);ba=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);
h.quit&&(ea=h.quit);var ha;h.wasmBinary&&(ha=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!==typeof WebAssembly&&n("no native wasm support detected");var ia,ja=!1;
function ka(a,b,c){var d={string:function(p){var r=0;if(null!==p&&void 0!==p&&0!==p){var q=(p.length<<2)+1;r=la(q);u(p,v,r,q)}return r},array:function(p){var r=la(p.length);x.set(p,r);return r}};a=h["_"+a];var e=[],f=0;if(c)for(var g=0;g<c.length;g++){var k=d[b[g]];k?(0===f&&(f=ma()),e[g]=k(c[g])):e[g]=c[g]}b=a.apply(null,e);b=function(p){0!==f&&oa(f);return p}(b)}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function y(a,b){return a?qa(v,a,b):""}
function u(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function z(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ra(a){var b=z(a)+1,c=A(b);c&&u(a,x,c,b);return c}function sa(a){var b=z(a)+1,c=la(b);u(a,x,c,b);return c}var ta,x,v,ua,va,B,wa,C,D,xa,ya=[],za=[],Aa=[],Ba=[],Ca=[];function Da(){var a=h.preRun.shift();ya.unshift(a)}var E=0,Ea=null,Fa=null;h.preloadedImages={};h.preloadedAudios={};
function n(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";m(a);ja=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ga(){return F.startsWith("data:application/octet-stream;base64,")}var F;F="SkyBoy.wasm";if(!Ga()){var Ha=F;F=h.locateFile?h.locateFile(Ha,l):l+Ha}function Ia(){var a=F;try{if(a==F&&ha)return new Uint8Array(ha);throw"both async and sync fetching of the wasm failed";}catch(b){n(b)}}
function Ja(){return ha||"function"!==typeof fetch?Promise.resolve().then(function(){return Ia()}):fetch(F,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+F+"'";return a.arrayBuffer()}).catch(function(){return Ia()})}
var G,Ka,Oa={153120:function(){document.getElementById("fileInput").style.visibility="hidden"},153208:function(a,b,c,d){var e=document.getElementById("fileInput");e.style.left=a+"px";e.style.top=b+"px";e.style.width=c+"px";e.style.height=d+"px";e.style.visibility="visible";if(""!=e.value){console.log(e.value);var f=new FileReader;a=e.files[0];f.addEventListener("loadend",function(){const k=new Uint8Array(f.result);var p="/offline/"+g;La(p,k);Ma(function(){});document.getElementById("fileStaging").value=
p});f.readAsArrayBuffer(a);var g=a.name;e.value=""}a=document.getElementById("fileStaging");e="";""!=a.value&&(e=a.value,a.value="");a=z(e)+1;b=A(a);u(e,v,b,a);return b},154232:function(){Ma(function(){})},154262:function(){Ma(function(){})},154292:function(){H("/offline");Na(I,"/offline");Ma(!0,function(){})}};function Pa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.Od;"number"===typeof c?void 0===b.zc?J(c)():J(c)(b.zc):c(void 0===b.zc?null:b.zc)}}}var Qa=[];
function J(a){var b=Qa[a];b||(a>=Qa.length&&(Qa.length=a+1),Qa[a]=b=xa.get(a));return b}function Ra(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Sa(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ra(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ta(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ua(a){if("/"===a)return"/";a=Sa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Va(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){n("randomDevice")}}
function Wa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ra(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Xa=[];function Ya(a,b){Xa[a]={input:[],Rb:[],ic:b};Za(a,$a)}
var $a={open:function(a){var b=Xa[a.node.tc];if(!b)throw new K(43);a.Pb=b;a.seekable=!1},close:function(a){a.Pb.ic.flush(a.Pb)},flush:function(a){a.Pb.ic.flush(a.Pb)},read:function(a,b,c,d){if(!a.Pb||!a.Pb.ic.Rc)throw new K(60);for(var e=0,f=0;f<d;f++){try{var g=a.Pb.ic.Rc(a.Pb)}catch(k){throw new K(29);}if(void 0===g&&0===e)throw new K(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Pb||!a.Pb.ic.Cc)throw new K(60);try{for(var e=
0;e<d;e++)a.Pb.ic.Cc(a.Pb,b[c+e])}catch(f){throw new K(29);}d&&(a.node.timestamp=Date.now());return e}},ab={Rc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;var c=Array(z(b)+1);b=u(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},Cc:function(a,b){null===b||10===b?(fa(qa(a.Rb,0)),a.Rb=[]):0!=b&&a.Rb.push(b)},
flush:function(a){a.Rb&&0<a.Rb.length&&(fa(qa(a.Rb,0)),a.Rb=[])}},bb={Cc:function(a,b){null===b||10===b?(m(qa(a.Rb,0)),a.Rb=[]):0!=b&&a.Rb.push(b)},flush:function(a){a.Rb&&0<a.Rb.length&&(m(qa(a.Rb,0)),a.Rb=[])}},L={Wb:null,Tb:function(){return L.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new K(63);L.Wb||(L.Wb={dir:{node:{Vb:L.Lb.Vb,Sb:L.Lb.Sb,jc:L.Lb.jc,sc:L.Lb.sc,Xc:L.Lb.Xc,xc:L.Lb.xc,vc:L.Lb.vc,uc:L.Lb.uc,wc:L.Lb.wc},stream:{dc:L.Nb.dc}},
file:{node:{Vb:L.Lb.Vb,Sb:L.Lb.Sb},stream:{dc:L.Nb.dc,read:L.Nb.read,write:L.Nb.write,Jc:L.Nb.Jc,Tc:L.Nb.Tc,Vc:L.Nb.Vc}},link:{node:{Vb:L.Lb.Vb,Sb:L.Lb.Sb,lc:L.Lb.lc},stream:{}},Lc:{node:{Vb:L.Lb.Vb,Sb:L.Lb.Sb},stream:cb}});c=db(a,b,c,d);16384===(c.mode&61440)?(c.Lb=L.Wb.dir.node,c.Nb=L.Wb.dir.stream,c.Mb={}):32768===(c.mode&61440)?(c.Lb=L.Wb.file.node,c.Nb=L.Wb.file.stream,c.Ob=0,c.Mb=null):40960===(c.mode&61440)?(c.Lb=L.Wb.link.node,c.Nb=L.Wb.link.stream):8192===(c.mode&61440)&&(c.Lb=L.Wb.Lc.node,
c.Nb=L.Wb.Lc.stream);c.timestamp=Date.now();a&&(a.Mb[b]=c,a.timestamp=c.timestamp);return c},pd:function(a){return a.Mb?a.Mb.subarray?a.Mb.subarray(0,a.Ob):new Uint8Array(a.Mb):new Uint8Array(0)},Oc:function(a,b){var c=a.Mb?a.Mb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Mb,a.Mb=new Uint8Array(b),0<a.Ob&&a.Mb.set(c.subarray(0,a.Ob),0))},Ad:function(a,b){if(a.Ob!=b)if(0==b)a.Mb=null,a.Ob=0;else{var c=a.Mb;a.Mb=new Uint8Array(b);c&&a.Mb.set(c.subarray(0,Math.min(b,
a.Ob)));a.Ob=b}},Lb:{Vb:function(a){var b={};b.Md=8192===(a.mode&61440)?a.id:1;b.Rd=a.id;b.mode=a.mode;b.Ud=1;b.uid=0;b.Pd=0;b.tc=a.tc;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ob:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Id=new Date(a.timestamp);b.Bc=new Date(a.timestamp);b.Kd=new Date(a.timestamp);b.hd=4096;b.Jd=Math.ceil(b.size/b.hd);return b},Sb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&
L.Ad(a,b.size)},jc:function(){throw eb[44];},sc:function(a,b,c,d){return L.createNode(a,b,c,d)},Xc:function(a,b,c){if(16384===(a.mode&61440)){try{var d=M(b,c)}catch(f){}if(d)for(var e in d.Mb)throw new K(55);}delete a.parent.Mb[a.name];a.parent.timestamp=Date.now();a.name=c;b.Mb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},xc:function(a,b){delete a.Mb[b];a.timestamp=Date.now()},vc:function(a,b){var c=M(a,b),d;for(d in c.Mb)throw new K(55);delete a.Mb[b];a.timestamp=Date.now()},uc:function(a){var b=
[".",".."],c;for(c in a.Mb)a.Mb.hasOwnProperty(c)&&b.push(c);return b},wc:function(a,b,c){a=L.createNode(a,b,41471,0);a.link=c;return a},lc:function(a){if(40960!==(a.mode&61440))throw new K(28);return a.link}},Nb:{read:function(a,b,c,d,e){var f=a.node.Mb;if(e>=a.node.Ob)return 0;a=Math.min(a.node.Ob-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Mb||a.Mb.subarray)){if(f)return a.Mb=
b.subarray(c,c+d),a.Ob=d;if(0===a.Ob&&0===e)return a.Mb=b.slice(c,c+d),a.Ob=d;if(e+d<=a.Ob)return a.Mb.set(b.subarray(c,c+d),e),d}L.Oc(a,e+d);if(a.Mb.subarray&&b.subarray)a.Mb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Mb[e+f]=b[c+f];a.Ob=Math.max(a.Ob,e+d);return d},dc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ob);if(0>b)throw new K(28);return b},Jc:function(a,b,c){L.Oc(a.node,b+c);a.node.Ob=Math.max(a.node.Ob,b+c)},Tc:function(a,b,c,d,e,f){if(0!==b)throw new K(28);
if(32768!==(a.node.mode&61440))throw new K(43);a=a.node.Mb;if(f&2||a.buffer!==ta){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;n();c=void 0;if(!c)throw new K(48);x.set(a,c)}else d=!1,c=a.byteOffset;return{Xd:c,Gd:d}},Vc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new K(43);if(e&2)return 0;L.Nb.write(a,b,0,d,c,!1);return 0}}},I={Mc:{},indexedDB:()=>{if("undefined"!==typeof indexedDB)return indexedDB;var a=null;"object"===typeof window&&
(a=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB);a||n("IDBFS used, but indexedDB not supported");return a},gd:21,cc:"FILE_DATA",Tb:function(a){return L.Tb.apply(null,arguments)},dd:(a,b,c)=>{I.qd(a,(d,e)=>{if(d)return c(d);I.rd(a,(f,g)=>{if(f)return c(f);I.xd(b?g:e,b?e:g,c)})})},od:(a,b)=>{var c=I.Mc[a];if(c)return b(null,c);try{var d=I.indexedDB().open(a,I.gd)}catch(e){return b(e)}if(!d)return b("Unable to connect to IndexedDB");d.onupgradeneeded=e=>{var f=e.target.result;
e=e.target.transaction;f=f.objectStoreNames.contains(I.cc)?e.objectStore(I.cc):f.createObjectStore(I.cc);f.indexNames.contains("timestamp")||f.createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=()=>{c=d.result;I.Mc[a]=c;b(null,c)};d.onerror=e=>{b(this.error);e.preventDefault()}},qd:(a,b)=>{function c(k){return"."!==k&&".."!==k}function d(k){return p=>Sa(k+"/"+p)}var e={};for(a=fb(a.kc).filter(c).map(d(a.kc));a.length;){var f=a.pop();try{var g=gb(f)}catch(k){return b(k)}16384===(g.mode&
61440)&&a.push.apply(a,fb(f).filter(c).map(d(f)));e[f]={timestamp:g.Bc}}return b(null,{type:"local",entries:e})},rd:(a,b)=>{var c={};I.od(a.kc,(d,e)=>{if(d)return b(d);try{var f=e.transaction([I.cc],"readonly");f.onerror=g=>{b(this.error);g.preventDefault()};f.objectStore(I.cc).index("timestamp").openKeyCursor().onsuccess=g=>{g=g.target.result;if(!g)return b(null,{type:"remote",db:e,entries:c});c[g.primaryKey]={timestamp:g.key};g.continue()}}catch(g){return b(g)}})},ud:(a,b)=>{try{var c=N(a).node;
var d=gb(a)}catch(e){return b(e)}return 16384===(d.mode&61440)?b(null,{timestamp:d.Bc,mode:d.mode}):32768===(d.mode&61440)?(c.Mb=L.pd(c),b(null,{timestamp:d.Bc,mode:d.mode,contents:c.Mb})):b(Error("node type not supported"))},Cd:(a,b,c)=>{try{if(16384===(b.mode&61440))for(var d=b.mode,e=a.split("/"),f="",g=0;g<e.length;++g){if(e[g]){f+="/"+e[g];try{H(f,d)}catch(w){if(20!=w.Xb)throw w;}}}else if(32768===(b.mode&61440))La(a,b.contents,{Kc:!0});else return c(Error("node type not supported"));var k=b.mode;
var p="string"===typeof a?N(a,{ec:!0}).node:a;if(!p.Lb.Sb)throw new K(63);p.Lb.Sb(p,{mode:k&4095|p.mode&-4096,timestamp:Date.now()});var r=b.timestamp,q=b.timestamp,t=N(a,{ec:!0}).node;t.Lb.Sb(t,{timestamp:Math.max(r,q)})}catch(w){return c(w)}c(null)},yd:(a,b)=>{try{N(a);var c=gb(a);if(16384===(c.mode&61440)){var d=N(a,{parent:!0}).node,e=Ua(a),f=M(d,e),g=hb(d,e,!0);if(g)throw new K(g);if(!d.Lb.vc)throw new K(63);if(f.fc)throw new K(10);d.Lb.vc(d,e);ib(f)}else if(32768===(c.mode&61440)){var k=N(a,
{parent:!0}).node;if(!k)throw new K(44);var p=Ua(a),r=M(k,p),q=hb(k,p,!1);if(q)throw new K(q);if(!k.Lb.xc)throw new K(63);if(r.fc)throw new K(10);k.Lb.xc(k,p);ib(r)}}catch(t){return b(t)}b(null)},vd:(a,b,c)=>{a=a.get(b);a.onsuccess=d=>{c(null,d.target.result)};a.onerror=d=>{c(this.error);d.preventDefault()}},Dd:(a,b,c,d)=>{try{var e=a.put(c,b)}catch(f){d(f);return}e.onsuccess=()=>{d(null)};e.onerror=f=>{d(this.error);f.preventDefault()}},zd:(a,b,c)=>{a=a.delete(b);a.onsuccess=()=>{c(null)};a.onerror=
d=>{c(this.error);d.preventDefault()}},xd:(a,b,c)=>{function d(q){if(q&&!k)return k=!0,c(q)}var e=0,f=[];Object.keys(a.entries).forEach(function(q){var t=a.entries[q],w=b.entries[q];w&&t.timestamp.getTime()==w.timestamp.getTime()||(f.push(q),e++)});var g=[];Object.keys(b.entries).forEach(function(q){a.entries[q]||(g.push(q),e++)});if(!e)return c(null);var k=!1,p=("remote"===a.type?a.db:b.db).transaction([I.cc],"readwrite"),r=p.objectStore(I.cc);p.onerror=q=>{d(this.error);q.preventDefault()};p.oncomplete=
()=>{k||c(null)};f.sort().forEach(q=>{"local"===b.type?I.vd(r,q,(t,w)=>{if(t)return d(t);I.Cd(q,w,d)}):I.ud(q,(t,w)=>{if(t)return d(t);I.Dd(r,q,w,d)})});g.sort().reverse().forEach(q=>{"local"===b.type?I.yd(q,d):I.zd(r,q,d)})}},jb=null,kb={},lb=[],mb=1,O=null,nb=!0,K=null,eb={},qb=0,N=(a,b={})=>{a=Wa("/",a);if(!a)return{path:"",node:null};var c={Pc:!0,Dc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Dc)throw new K(32);a=Ra(a.split("/").filter(g=>!!g),!1);var e=jb;c="/";for(d=0;d<a.length;d++){var f=
d===a.length-1;if(f&&b.parent)break;e=M(e,a[d]);c=Sa(c+"/"+a[d]);e.fc&&(!f||f&&b.Pc)&&(e=e.fc.root);if(!f||b.ec)for(f=0;40960===(e.mode&61440);)if(e=rb(c),c=Wa(Ta(c),e),e=N(c,{Dc:b.Dc}).node,40<f++)throw new K(32);}return{path:c,node:e}},sb=a=>{for(var b;;){if(a===a.parent)return a=a.Tb.kc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},tb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length},ib=a=>{var b=tb(a.parent.id,a.name);if(O[b]===
a)O[b]=a.hc;else for(b=O[b];b;){if(b.hc===a){b.hc=a.hc;break}b=b.hc}},M=(a,b)=>{var c;if(c=(c=ub(a,"x"))?c:a.Lb.jc?0:2)throw new K(c,a);for(c=O[tb(a.id,b)];c;c=c.hc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Lb.jc(a,b)},db=(a,b,c,d)=>{a=new vb(a,b,c,d);b=tb(a.parent.id,a.name);a.hc=O[b];return O[b]=a},wb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},xb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},ub=(a,b)=>{if(nb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&
!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},yb=(a,b)=>{try{return M(a,b),20}catch(c){}return ub(a,"wx")},hb=(a,b,c)=>{try{var d=M(a,b)}catch(e){return e.Xb}if(a=ub(a,"wx"))return a;if(c){if(16384!==(d.mode&61440))return 54;if(d===d.parent||"/"===sb(d))return 10}else if(16384===(d.mode&61440))return 31;return 0},zb=(a=0,b=4096)=>{for(;a<=b;a++)if(!lb[a])return a;throw new K(33);},Bb=(a,b)=>{Ab||(Ab=function(){},Ab.prototype={});var c=new Ab,d;for(d in a)c[d]=a[d];
a=c;b=zb(b,void 0);a.ac=b;return lb[b]=a},cb={open:a=>{a.Nb=kb[a.node.tc].Nb;a.Nb.open&&a.Nb.open(a)},dc:()=>{throw new K(70);}},Za=(a,b)=>{kb[a]={Nb:b}},Cb=()=>{for(var a=[],b=[jb.Tb];b.length;){var c=b.pop();a.push(c);b.push.apply(b,c.Uc)}return a},Ma=(a,b)=>{function c(g){qb--;return b(g)}function d(g){if(g){if(!d.ld)return d.ld=!0,c(g)}else++f>=e.length&&c(null)}"function"===typeof a&&(b=a,a=!1);qb++;1<qb&&m("warning: "+qb+" FS.syncfs operations in flight at once, probably just doing extra work");
var e=Cb(),f=0;e.forEach(g=>{if(!g.type.dd)return d(null);g.type.dd(g,a,d)})},Na=(a,b)=>{var c="/"===b,d=!b;if(c&&jb)throw new K(10);if(!c&&!d){var e=N(b,{Pc:!1});b=e.path;e=e.node;if(e.fc)throw new K(10);if(16384!==(e.mode&61440))throw new K(54);}b={type:a,Vd:{},kc:b,Uc:[]};a=a.Tb(b);a.Tb=b;b.root=a;c?jb=a:e&&(e.fc=b,e.Tb&&e.Tb.Uc.push(b))},Db=(a,b,c)=>{var d=N(a,{parent:!0}).node;a=Ua(a);if(!a||"."===a||".."===a)throw new K(28);var e=yb(d,a);if(e)throw new K(e);if(!d.Lb.sc)throw new K(63);return d.Lb.sc(d,
a,b,c)},H=(a,b)=>Db(a,(void 0!==b?b:511)&1023|16384,0),Eb=(a,b,c)=>{"undefined"===typeof c&&(c=b,b=438);Db(a,b|8192,c)},Fb=(a,b)=>{if(!Wa(a))throw new K(44);var c=N(b,{parent:!0}).node;if(!c)throw new K(44);b=Ua(b);var d=yb(c,b);if(d)throw new K(d);if(!c.Lb.wc)throw new K(63);c.Lb.wc(c,b,a)},fb=a=>{a=N(a,{ec:!0}).node;if(!a.Lb.uc)throw new K(54);return a.Lb.uc(a)},rb=a=>{a=N(a).node;if(!a)throw new K(44);if(!a.Lb.lc)throw new K(28);return Wa(sb(a.parent),a.Lb.lc(a))},gb=a=>{a=N(a,{ec:!0}).node;if(!a)throw new K(44);
if(!a.Lb.Vb)throw new K(63);return a.Lb.Vb(a)},P=(a,b,c,d)=>{if(""===a)throw new K(44);if("string"===typeof b){var e=wb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Sa(a);try{f=N(a,{ec:!(b&131072)}).node}catch(g){}}e=!1;if(b&64)if(f){if(b&128)throw new K(20);}else f=Db(a,c,0),e=!0;if(!f)throw new K(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new K(54);
if(!e&&(c=f?40960===(f.mode&61440)?32:16384===(f.mode&61440)&&("r"!==xb(b)||b&512)?31:ub(f,xb(b)):44))throw new K(c);if(b&512){c=f;c="string"===typeof c?N(c,{ec:!0}).node:c;if(!c.Lb.Sb)throw new K(63);if(16384===(c.mode&61440))throw new K(31);if(32768!==(c.mode&61440))throw new K(28);if(e=ub(c,"w"))throw new K(e);c.Lb.Sb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Bb({node:f,path:sb(f),flags:b,seekable:!0,position:0,Nb:f.Nb,Ed:[],error:!1},d);d.Nb.open&&d.Nb.open(d);!h.logReadFiles||b&1||(Gb||(Gb=
{}),a in Gb||(Gb[a]=1));return d},Hb=a=>{if(null===a.ac)throw new K(8);a.Ac&&(a.Ac=null);try{a.Nb.close&&a.Nb.close(a)}catch(b){throw b;}finally{lb[a.ac]=null}a.ac=null},Ib=(a,b,c)=>{if(null===a.ac)throw new K(8);if(!a.seekable||!a.Nb.dc)throw new K(70);if(0!=c&&1!=c&&2!=c)throw new K(28);a.position=a.Nb.dc(a,b,c);a.Ed=[]},Jb=(a,b,c,d,e)=>{var f=void 0;if(0>d||0>f)throw new K(28);if(null===a.ac)throw new K(8);if(0===(a.flags&2097155))throw new K(8);if(16384===(a.node.mode&61440))throw new K(31);if(!a.Nb.write)throw new K(28);
a.seekable&&a.flags&1024&&Ib(a,0,2);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new K(70);b=a.Nb.write(a,b,c,d,f,e);g||(a.position+=b);return b},La=(a,b,c={})=>{c.flags=c.flags||577;a=P(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(z(b)+1);b=u(b,d,0,d.length);Jb(a,d,0,b,c.Kc)}else if(ArrayBuffer.isView(b))Jb(a,b,0,b.byteLength,c.Kc);else throw Error("Unsupported data type");Hb(a)},Kb=()=>{K||(K=function(a,b){this.node=b;this.Bd=function(c){this.Xb=c};
this.Bd(a);this.message="FS error"},K.prototype=Error(),K.prototype.constructor=K,[44].forEach(a=>{eb[a]=new K(a);eb[a].stack="<generic error, no stack>"}))},Lb,Mb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ob=(a,b,c)=>{a=Sa("/dev/"+a);var d=Mb(!!b,!!c);Nb||(Nb=64);var e=Nb++<<8|0;Za(e,{open:f=>{f.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(f,g,k,p)=>{for(var r=0,q=0;q<p;q++){try{var t=b()}catch(w){throw new K(29);}if(void 0===t&&0===r)throw new K(6);if(null===t||void 0===
t)break;r++;g[k+q]=t}r&&(f.node.timestamp=Date.now());return r},write:(f,g,k,p)=>{for(var r=0;r<p;r++)try{c(g[k+r])}catch(q){throw new K(29);}p&&(f.node.timestamp=Date.now());return r}});Eb(a,d,e)},Nb,Q={},Ab,Gb,Pb=void 0;function R(){Pb+=4;return B[Pb-4>>2]}function S(a){a=lb[a];if(!a)throw new K(8);return a}
function Qb(a,b,c){function d(p){return(p=p.toTimeString().match(/\(([A-Za-z ]+)\)$/))?p[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var k=g.getTimezoneOffset();B[a>>2]=60*Math.max(e,k);B[b>>2]=Number(e!=k);a=d(f);b=d(g);a=ra(a);b=ra(b);k<e?(B[c>>2]=a,B[c+4>>2]=b):(B[c>>2]=b,B[c+4>>2]=a)}function Rb(a,b,c){Rb.jd||(Rb.jd=!0,Qb(a,b,c))}var Sb=[],Tb=0;function Ub(){for(var a=T.length-1;0<=a;--a)Vb(a);T=[];Wb=[]}var Wb=[];
function Xb(){if(Tb&&Yb.oc)for(var a=0;a<Wb.length;++a){var b=Wb[a];Wb.splice(a,1);--a;b.$d.apply(null,b.Hd)}}var T=[];function Vb(a){var b=T[a];b.target.removeEventListener(b.Ub,b.md,b.Yb);T.splice(a,1)}function U(a){function b(d){++Tb;Yb=a;Xb();a.bc(d);Xb();--Tb}if(a.$b)a.md=b,a.target.addEventListener(a.Ub,b,a.Yb),T.push(a),Zb||(Ba.push(Ub),Zb=!0);else for(var c=0;c<T.length;++c)T[c].target==a.target&&T[c].Ub==a.Ub&&Vb(c--)}var Zb,Yb,$b,ac,bc,cc,dc,ec,fc=[0,document,window];
function V(a){a=2<a?y(a):a;return fc[a]||document.querySelector(a)}function gc(a){return 0>fc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function hc(a,b,c,d,e,f){$b||($b=A(176));a={target:V(a),oc:!0,Ub:f,$b:d,bc:function(g){var k=$b;D[k>>3]=g.timeStamp;var p=k>>2;B[p+2]=g.location;B[p+3]=g.ctrlKey;B[p+4]=g.shiftKey;B[p+5]=g.altKey;B[p+6]=g.metaKey;B[p+7]=g.repeat;B[p+8]=g.charCode;B[p+9]=g.keyCode;B[p+10]=g.which;u(g.key||"",v,k+44,32);u(g.code||"",v,k+76,32);u(g.char||"",v,k+108,32);u(g.locale||"",v,k+140,32);J(d)(e,k,b)&&g.preventDefault()},Yb:c};U(a)}
function ic(a,b,c){D[a>>3]=b.timeStamp;a>>=2;B[a+2]=b.screenX;B[a+3]=b.screenY;B[a+4]=b.clientX;B[a+5]=b.clientY;B[a+6]=b.ctrlKey;B[a+7]=b.shiftKey;B[a+8]=b.altKey;B[a+9]=b.metaKey;ua[2*a+20]=b.button;ua[2*a+21]=b.buttons;B[a+11]=b.movementX;B[a+12]=b.movementY;c=gc(c);B[a+13]=b.clientX-c.left;B[a+14]=b.clientY-c.top}
function jc(a,b,c,d,e,f){ac||(ac=A(72));a=V(a);U({target:a,oc:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Ub:f,$b:d,bc:function(g){g=g||event;ic(ac,g,a);J(d)(e,ac,b)&&g.preventDefault()},Yb:c})}
function kc(a,b,c,d,e){bc||(bc=A(260));U({target:a,Ub:e,$b:d,bc:function(f){f=f||event;var g=bc,k=document.pointerLockElement||document.Gc||document.Ic||document.Hc;B[g>>2]=!!k;var p=k&&k.id?k.id:"";u(k?k==window?"#window":k==screen?"#screen":k&&k.nodeName?k.nodeName:"":"",v,g+4,128);u(p,v,g+132,128);J(d)(20,g,b)&&f.preventDefault()},Yb:c})}function lc(a,b,c,d,e){U({target:a,Ub:e,$b:d,bc:function(f){f=f||event;J(d)(38,0,b)&&f.preventDefault()},Yb:c})}
function mc(a,b,c,d){cc||(cc=A(36));a=V(a);U({target:a,Ub:"resize",$b:d,bc:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=cc;B[g>>2]=e.detail;B[g+4>>2]=f.clientWidth;B[g+8>>2]=f.clientHeight;B[g+12>>2]=innerWidth;B[g+16>>2]=innerHeight;B[g+20>>2]=outerWidth;B[g+24>>2]=outerHeight;B[g+28>>2]=pageXOffset;B[g+32>>2]=pageYOffset;J(d)(10,g,b)&&e.preventDefault()}}},Yb:c})}
function nc(a,b,c,d,e,f){dc||(dc=A(1696));a=V(a);U({target:a,oc:"touchstart"==f||"touchend"==f,Ub:f,$b:d,bc:function(g){for(var k,p={},r=g.touches,q=0;q<r.length;++q)k=r[q],k.Sc=k.Wc=0,p[k.identifier]=k;for(q=0;q<g.changedTouches.length;++q)k=g.changedTouches[q],k.Sc=1,p[k.identifier]=k;for(q=0;q<g.targetTouches.length;++q)p[g.targetTouches[q].identifier].Wc=1;r=dc;D[r>>3]=g.timeStamp;var t=r>>2;B[t+3]=g.ctrlKey;B[t+4]=g.shiftKey;B[t+5]=g.altKey;B[t+6]=g.metaKey;t+=7;var w=gc(a),na=0;for(q in p)if(k=
p[q],B[t]=k.identifier,B[t+1]=k.screenX,B[t+2]=k.screenY,B[t+3]=k.clientX,B[t+4]=k.clientY,B[t+5]=k.pageX,B[t+6]=k.pageY,B[t+7]=k.Sc,B[t+8]=k.Wc,B[t+9]=k.clientX-w.left,B[t+10]=k.clientY-w.top,t+=13,31<++na)break;B[r+8>>2]=na;J(d)(e,r,b)&&g.preventDefault()},Yb:c})}function oc(a,b,c,d,e,f){a={target:V(a),Ub:f,$b:d,bc:function(g){g=g||event;J(d)(e,0,b)&&g.preventDefault()},Yb:c};U(a)}
function pc(a,b,c,d){ec||(ec=A(104));U({target:a,oc:!0,Ub:"wheel",$b:d,bc:function(e){e=e||event;var f=ec;ic(f,e,a);D[f+72>>3]=e.deltaX;D[f+80>>3]=e.deltaY;D[f+88>>3]=e.deltaZ;B[f+96>>2]=e.deltaMode;J(d)(9,f,b)&&e.preventDefault()},Yb:c})}
function qc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function rc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function tc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function uc(a){a.Td=a.getExtension("WEBGL_multi_draw")}
var vc=1,wc=[],W=[],xc=[],yc=[],zc=[],X=[],Ac=[],Bc={};function Y(a){Cc||(Cc=a)}function Dc(a){for(var b=vc++,c=a.length;c<b;c++)a[c]=null;return b}function Ec(a,b){a.Qc||(a.Qc=a.getContext,a.getContext=function(d,e){e=a.Qc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Fc(c,b):0}function Fc(a,b){var c=Dc(Ac),d={Qd:c,attributes:b,version:b.wd,yc:a};a.canvas&&(a.canvas.Fd=d);Ac[c]=d;("undefined"===typeof b.Nc||b.Nc)&&Gc(d);return c}
function Gc(a){a||(a=Hc);if(!a.sd){a.sd=!0;var b=a.yc;qc(b);rc(b);tc(b);b.Nd=b.getExtension("EXT_disjoint_timer_query");uc(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Cc,Hc,Ic=["default","low-power","high-performance"];function Jc(a,b,c,d){for(var e=0;e<a;e++){var f=Z[c](),g=f&&Dc(d);f?(f.name=g,d[g]=f):Y(1282);B[b+4*e>>2]=g}}
function Kc(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)B[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Y(1280);m("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:Y(1280);m("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}B[b>>2]=c}else Y(1281)}function Lc(a){var b=z(a)+1,c=A(b);u(a,v,c,b);return c}
function Mc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Nc(a){var b=Z.kd;if(b){var c=b.nc[a];"number"===typeof c&&(b.nc[a]=c=Z.getUniformLocation(b,b.ed[a]+(0<c?"["+c+"]":"")));return c}Y(1282)}var Oc=[];function vb(a,b,c,d){a||(a=this);this.parent=a;this.Tb=a.Tb;this.fc=null;this.id=mb++;this.name=b;this.mode=c;this.Lb={};this.Nb={};this.tc=d}
Object.defineProperties(vb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Kb();O=Array(4096);Na(L,"/");H("/tmp");H("/home");H("/home/web_user");
(()=>{H("/dev");Za(259,{read:()=>0,write:(b,c,d,e)=>e});Eb("/dev/null",259);Ya(1280,ab);Ya(1536,bb);Eb("/dev/tty",1280);Eb("/dev/tty1",1536);var a=Va();Ob("random",a);Ob("urandom",a);H("/dev/shm");H("/dev/shm/tmp")})();(()=>{H("/proc");var a=H("/proc/self");H("/proc/self/fd");Na({Tb:()=>{var b=db(a,"fd",16895,73);b.Lb={jc:(c,d)=>{var e=lb[+d];if(!e)throw new K(8);c={parent:null,Tb:{kc:"fake"},Lb:{lc:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
for(var Z,Pc=new Float32Array(288),Qc=0;288>Qc;++Qc)Oc[Qc]=Pc.subarray(0,Qc+1);
var Yc={pa:function(a,b,c){Pb=c;try{var d=S(a);switch(b){case 0:var e=R();return 0>e?-28:P(d.path,d.flags,0,e).ac;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=R(),d.flags|=e,0;case 5:return e=R(),ua[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return B[Rc()>>2]=28,-1;default:return-28}}catch(f){if("undefined"===typeof Q||!(f instanceof K))throw f;return-f.Xb}},eb:function(a,b,c){Pb=c;try{var d=S(a);switch(b){case 21509:case 21505:return d.Pb?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Pb?
0:-59;case 21519:if(!d.Pb)return-59;var e=R();return B[e>>2]=0;case 21520:return d.Pb?-28:-59;case 21531:a=e=R();if(!d.Nb.td)throw new K(59);return d.Nb.td(d,b,a);case 21523:return d.Pb?0:-59;case 21524:return d.Pb?0:-59;default:n("bad ioctl syscall "+b)}}catch(f){if("undefined"===typeof Q||!(f instanceof K))throw f;return-f.Xb}},fb:function(a,b,c){Pb=c;try{var d=y(a),e=c?R():0;return P(d,b,e).ac}catch(f){if("undefined"===typeof Q||!(f instanceof K))throw f;return-f.Xb}},ab:function(a,b){a=new Date(1E3*
B[a>>2]);B[b>>2]=a.getSeconds();B[b+4>>2]=a.getMinutes();B[b+8>>2]=a.getHours();B[b+12>>2]=a.getDate();B[b+16>>2]=a.getMonth();B[b+20>>2]=a.getFullYear()-1900;B[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);B[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;B[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();B[b+32>>2]=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0},bb:Rb,k:function(a,b,c){Sb.length=0;var d;for(c>>=2;d=v[b++];)(d=
105>d)&&c&1&&c++,Sb.push(d?D[c++>>1]:B[c]),++c;return Oa[a].apply(null,Sb)},X:function(){return devicePixelRatio},_:function(a,b,c){a=V(a);if(!a)return-4;a=gc(a);D[b>>3]=a.width;D[c>>3]=a.height;return 0},gb:function(a,b,c){v.copyWithin(a,b,b+c)},Wa:function(a,b){function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},y:function(){n("OOM")},U:function(a,b,c){a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0},ia:function(a,b,c,d){hc(a,b,c,d,2,"keydown");return 0},ga:function(a,
b,c,d){hc(a,b,c,d,1,"keypress");return 0},ha:function(a,b,c,d){hc(a,b,c,d,3,"keyup");return 0},ra:function(a,b,c,d){jc(a,b,c,d,5,"mousedown");return 0},la:function(a,b,c,d){jc(a,b,c,d,33,"mouseenter");return 0},ka:function(a,b,c,d){jc(a,b,c,d,34,"mouseleave");return 0},ma:function(a,b,c,d){jc(a,b,c,d,8,"mousemove");return 0},oa:function(a,b,c,d){jc(a,b,c,d,6,"mouseup");return 0},ba:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Gc||document.body.Ic||
document.body.Hc))return-1;a=V(a);if(!a)return-4;kc(a,b,c,d,"pointerlockchange");kc(a,b,c,d,"mozpointerlockchange");kc(a,b,c,d,"webkitpointerlockchange");kc(a,b,c,d,"mspointerlockchange");return 0},aa:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Gc||document.body.Ic||document.body.Hc))return-1;a=V(a);if(!a)return-4;lc(a,b,c,d,"pointerlockerror");lc(a,b,c,d,"mozpointerlockerror");lc(a,b,c,d,"webkitpointerlockerror");lc(a,b,c,d,"mspointerlockerror");return 0},Sa:function(a,
b,c,d){mc(a,b,c,d);return 0},ca:function(a,b,c,d){nc(a,b,c,d,25,"touchcancel");return 0},da:function(a,b,c,d){nc(a,b,c,d,23,"touchend");return 0},ea:function(a,b,c,d){nc(a,b,c,d,24,"touchmove");return 0},fa:function(a,b,c,d){nc(a,b,c,d,22,"touchstart");return 0},$:function(a,b,c,d){oc(a,b,c,d,31,"webglcontextlost");return 0},Z:function(a,b,c,d){oc(a,b,c,d,32,"webglcontextrestored");return 0},ja:function(a,b,c,d){a=V(a);return"undefined"!==typeof a.onwheel?(pc(a,b,c,d),0):-1},L:function(a,b){b>>=2;
b={alpha:!!B[b],depth:!!B[b+1],stencil:!!B[b+2],antialias:!!B[b+3],premultipliedAlpha:!!B[b+4],preserveDrawingBuffer:!!B[b+5],powerPreference:Ic[B[b+6]],failIfMajorPerformanceCaveat:!!B[b+7],wd:B[b+8],Sd:B[b+9],Nc:B[b+10],nd:B[b+11],Wd:B[b+12],Yd:B[b+13]};a=V(a);return!a||b.nd?0:Ec(a,b)},sb:function(a,b){a=Ac[a];b=y(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&qc(Z);"OES_vertex_array_object"==b&&rc(Z);"WEBGL_draw_buffers"==b&&tc(Z);"WEBGL_multi_draw"==b&&uc(Z);return!!a.yc.getExtension(b)},
Fa:function(a){a>>=2;for(var b=0;14>b;++b)B[a+b]=0;B[a]=B[a+1]=B[a+3]=B[a+4]=B[a+8]=B[a+10]=1},ya:function(a){Hc=Ac[a];h.Ld=Z=Hc&&Hc.yc;return!a||Z?0:-5},na:function(a){try{var b=S(a);Hb(b);return 0}catch(c){if("undefined"===typeof Q||!(c instanceof K))throw c;return c.Xb}},db:function(a,b,c,d){try{a:{for(var e=S(a),f=a=0;f<c;f++){var g=B[b+(8*f+4)>>2],k=e,p=B[b+8*f>>2],r=g,q=void 0,t=x;if(0>r||0>q)throw new K(28);if(null===k.ac)throw new K(8);if(1===(k.flags&2097155))throw new K(8);if(16384===(k.node.mode&
61440))throw new K(31);if(!k.Nb.read)throw new K(28);var w="undefined"!==typeof q;if(!w)q=k.position;else if(!k.seekable)throw new K(70);var na=k.Nb.read(k,t,p,r,q);w||(k.position+=na);var ob=na;if(0>ob){var sc=-1;break a}a+=ob;if(ob<g)break}sc=a}B[d>>2]=sc;return 0}catch(pb){if("undefined"===typeof Q||!(pb instanceof K))throw pb;return pb.Xb}},$a:function(a,b,c,d,e){try{var f=S(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Ib(f,a,d);Ka=[f.position>>>0,(G=f.position,
1<=+Math.abs(G)?0<G?(Math.min(+Math.floor(G/4294967296),4294967295)|0)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];B[e>>2]=Ka[0];B[e+4>>2]=Ka[1];f.Ac&&0===a&&0===d&&(f.Ac=null);return 0}catch(g){if("undefined"===typeof Q||!(g instanceof K))throw g;return g.Xb}},cb:function(a,b,c,d){try{a:{for(var e=S(a),f=a=0;f<c;f++){var g=Jb(e,x,B[b+8*f>>2],B[b+(8*f+4)>>2]);if(0>g){var k=-1;break a}a+=g}k=a}B[d>>2]=k;return 0}catch(p){if("undefined"===typeof Q||!(p instanceof K))throw p;return p.Xb}},b:function(a){Z.activeTexture(a)},
W:function(a,b){Z.attachShader(W[a],X[b])},c:function(a,b){Z.bindBuffer(a,wc[b])},S:function(a,b){Z.bindFramebuffer(a,xc[b])},Oa:function(a,b){Z.bindRenderbuffer(a,yc[b])},a:function(a,b){Z.bindTexture(a,zc[b])},K:function(a,b,c,d){Z.blendColor(a,b,c,d)},M:function(a,b){Z.blendEquationSeparate(a,b)},N:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},Qa:function(a,b,c,d){Z.bufferData(a,c?v.subarray(c,c+b):b,d)},o:function(a,b,c,d){Z.bufferSubData(a,b,v.subarray(d,d+c))},Ca:function(a){Z.clear(a)},Ea:function(a,
b,c,d){Z.clearColor(a,b,c,d)},R:function(a){Z.clearDepth(a)},Da:function(a){Z.clearStencil(a)},i:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},ib:function(a){Z.compileShader(X[a])},La:function(a,b,c,d,e,f,g,k){Z.compressedTexImage2D(a,b,c,d,e,f,k?v.subarray(k,k+g):null)},Ja:function(){var a=Dc(W),b=Z.createProgram();b.name=a;b.rc=b.pc=b.qc=0;b.Fc=1;W[a]=b;return a},kb:function(a){var b=Dc(X);X[b]=Z.createShader(a);return b},J:function(a){Z.cullFace(a)},ob:function(a,b){for(var c=0;c<a;c++){var d=
B[b+4*c>>2],e=wc[d];e&&(Z.deleteBuffer(e),e.name=0,wc[d]=null)}},h:function(a,b){for(var c=0;c<a;++c){var d=B[b+4*c>>2],e=xc[d];e&&(Z.deleteFramebuffer(e),e.name=0,xc[d]=null)}},x:function(a){if(a){var b=W[a];b?(Z.deleteProgram(b),b.name=0,W[a]=null):Y(1281)}},sa:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=yc[d];e&&(Z.deleteRenderbuffer(e),e.name=0,yc[d]=null)}},w:function(a){if(a){var b=X[a];b?(Z.deleteShader(b),X[a]=null):Y(1281)}},nb:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>
2],e=zc[d];e&&(Z.deleteTexture(e),e.name=0,zc[d]=null)}},u:function(a){Z.depthFunc(a)},v:function(a){Z.depthMask(!!a)},d:function(a){Z.disable(a)},H:function(a){Z.disableVertexAttribArray(a)},wa:function(a,b,c){Z.drawArrays(a,b,c)},xa:function(a,b,c,d){Z.drawElements(a,b,c,d)},e:function(a){Z.enable(a)},za:function(a){Z.enableVertexAttribArray(a)},I:function(a){Z.frontFace(a)},Ra:function(a,b){Jc(a,b,"createBuffer",wc)},Pa:function(a,b){Jc(a,b,"createRenderbuffer",yc)},Ma:function(a,b){Jc(a,b,"createTexture",
zc)},Ga:function(a,b){return Z.getAttribLocation(W[a],y(b))},f:function(a,b){Kc(a,b)},Ha:function(a,b,c,d){a=Z.getProgramInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&d?u(a,v,d,b):0;c&&(B[c>>2]=b)},V:function(a,b,c){if(c)if(a>=vc)Y(1281);else if(a=W[a],35716==b)a=Z.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.rc)for(b=0;b<Z.getProgramParameter(a,35718);++b)a.rc=Math.max(a.rc,Z.getActiveUniform(a,b).name.length+1);B[c>>2]=a.rc}else if(35722==
b){if(!a.pc)for(b=0;b<Z.getProgramParameter(a,35721);++b)a.pc=Math.max(a.pc,Z.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.pc}else if(35381==b){if(!a.qc)for(b=0;b<Z.getProgramParameter(a,35382);++b)a.qc=Math.max(a.qc,Z.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.qc}else B[c>>2]=Z.getProgramParameter(a,b);else Y(1281)},hb:function(a,b,c,d){a=Z.getShaderInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?u(a,v,d,b):0;c&&(B[c>>2]=b)},qa:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(X[a]),
null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=Z.getShaderSource(X[a]),B[c>>2]=a?a.length+1:0):B[c>>2]=Z.getShaderParameter(X[a],b):Y(1281)},Ta:function(a){var b=Bc[a];if(!b){switch(a){case 7939:b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Lc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||Y(1280);b=b&&Lc(b);break;case 7938:b=Lc("OpenGL ES 2.0 ("+Z.getParameter(7938)+")");break;case 35724:b=Z.getParameter(35724);
var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Lc(b);break;default:Y(1280)}Bc[a]=b}return b},n:function(a,b){b=y(b);if(a=W[a]){var c=a,d=c.nc,e=c.fd,f;if(!d)for(c.nc=d={},c.ed={},f=0;f<Z.getProgramParameter(c,35718);++f){var g=Z.getActiveUniform(c,f);var k=g.name;g=g.size;var p=Mc(k);p=0<p?k.slice(0,p):k;var r=c.Fc;c.Fc+=g;e[p]=[g,r];for(k=0;k<g;++k)d[r]=k,c.ed[r++]=p}c=a.nc;d=0;e=b;f=Mc(b);0<f&&(d=parseInt(b.slice(f+
1))>>>0,e=b.slice(0,f));if((e=a.fd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Z.getUniformLocation(a,b)))return d}else Y(1281);return-1},Ia:function(a){a=W[a];Z.linkProgram(a);a.nc=0;a.fd={}},Q:function(a,b){Z.polygonOffset(a,b)},Na:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},l:function(a,b,c,d){Z.scissor(a,b,c,d)},jb:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=d?B[d+4*f>>2]:-1;e+=y(B[c+4*f>>2],0>g?void 0:g)}Z.shaderSource(X[a],e)},mb:function(a,b,c){Z.stencilFunc(a,b,c)},P:function(a,b,c,d){Z.stencilFuncSeparate(a,
b,c,d)},t:function(a){Z.stencilMask(a)},lb:function(a,b,c){Z.stencilOp(a,b,c)},O:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},Ka:function(a,b,c,d,e,f,g,k,p){var r=Z,q=r.texImage2D;if(p){var t=k-5120;t=1==t?v:4==t?B:6==t?C:5==t||28922==t?wa:va;var w=31-Math.clz32(t.BYTES_PER_ELEMENT);p=t.subarray(p>>w,p+e*(d*({5:3,6:4,8:2,29502:3,29504:4}[g-6402]||1)*(1<<w)+4-1&-4)>>w)}else p=null;q.call(r,a,b,c,d,e,f,g,k,p)},g:function(a,b,c){Z.texParameteri(a,b,c)},G:function(a,b,c){if(288>=b)for(var d=Oc[b-1],
e=0;e<b;++e)d[e]=C[c+4*e>>2];else d=C.subarray(c>>2,c+4*b>>2);Z.uniform1fv(Nc(a),d)},T:function(a,b){Z.uniform1i(Nc(a),b)},F:function(a,b,c){if(144>=b)for(var d=Oc[2*b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);Z.uniform2fv(Nc(a),d)},E:function(a,b,c){if(96>=b)for(var d=Oc[3*b-1],e=0;e<3*b;e+=3)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2];else d=C.subarray(c>>2,c+12*b>>2);Z.uniform3fv(Nc(a),d)},D:function(a,b,c){if(72>=b){var d=Oc[4*
b-1],e=C;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=C.subarray(c>>2,c+16*b>>2);Z.uniform4fv(Nc(a),d)},C:function(a,b,c,d){if(18>=b){var e=Oc[16*b-1],f=C;d>>=2;for(var g=0;g<16*b;g+=16){var k=d+g;e[g]=f[k];e[g+1]=f[k+1];e[g+2]=f[k+2];e[g+3]=f[k+3];e[g+4]=f[k+4];e[g+5]=f[k+5];e[g+6]=f[k+6];e[g+7]=f[k+7];e[g+8]=f[k+8];e[g+9]=f[k+9];e[g+10]=f[k+10];e[g+11]=f[k+11];e[g+12]=f[k+12];e[g+13]=f[k+13];e[g+14]=f[k+14];e[g+15]=f[k+15]}}else e=C.subarray(d>>
2,d+64*b>>2);Z.uniformMatrix4fv(Nc(a),!!c,e)},j:function(a){a=W[a];Z.useProgram(a);Z.kd=a},Aa:function(a,b){Z.vertexAttribDivisor(a,b)},Ba:function(a,b,c,d,e,f){Z.vertexAttribPointer(a,b,c,!!d,e,f)},m:function(a,b,c,d){Z.viewport(a,b,c,d)},Za:function(){h.Yc=function(a){0!=Sc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.Yc)},Ya:function(){h.cd=function(a){a=a.clipboardData.getData("text");ka("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",
h.cd)},Xa:function(a){h.Zd=[];a=y(a);a=document.getElementById(a);h.Zc=function(b){b.stopPropagation();b.preventDefault()};h.$c=function(b){b.stopPropagation();b.preventDefault()};h.ad=function(b){b.stopPropagation();b.preventDefault()};h.bd=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;h.Ec=c;Tc(c.length);var d;for(d=0;d<c.length;d++)ka("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Uc(b.clientX,b.clientY)};a.addEventListener("dragenter",h.Zc,!1);a.addEventListener("dragleave",
h.$c,!1);a.addEventListener("dragover",h.ad,!1);a.addEventListener("drop",h.bd,!1)},r:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Vc()});document.body.append(a)},Y:function(a){return 0>a||a>=h.Ec.length?0:h.Ec[a].size},Ua:function(a,b,c,d,e){var f=new FileReader;f.onload=function(g){g=g.target.result;g.byteLength>d?Wc(a,0,1,b,0,c,d,e):(v.set(new Uint8Array(g),c),Wc(a,1,0,b,g.byteLength,
c,d,e))};f.onerror=function(){Wc(a,0,2,b,0,c,d,e)};f.readAsArrayBuffer(h.Ec[a])},q:function(){document.getElementById("_sokol_app_input_element").focus()},_a:function(a){a=y(a);h.mc=document.getElementById(a);h.mc||console.log("sokol_app.h: invalid target:"+a);h.mc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},rb:function(){window.removeEventListener("beforeunload",h.Yc)},qb:function(){window.removeEventListener("paste",h.cd)},pb:function(a){a=y(a);
a=document.getElementById(a);a.removeEventListener("dragenter",h.Zc);a.removeEventListener("dragleave",h.$c);a.removeEventListener("dragover",h.ad);a.removeEventListener("drop",h.bd)},z:function(){h.mc&&h.mc.requestPointerLock&&h.mc.requestPointerLock()},p:function(){document.getElementById("_sokol_app_input_element").blur()},Va:function(a){a=y(a);var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");
b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ta:function(){return h.Zb?h.Zb.bufferSize:0},va:function(a,b,c){h.Qb=null;h.Zb=null;"undefined"!==typeof AudioContext?h.Qb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?h.Qb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):
(h.Qb=null,console.log("sokol_audio.h: no WebAudio support"));return h.Qb?(console.log("sokol_audio.h: sample rate ",h.Qb.sampleRate),h.Zb=h.Qb.createScriptProcessor(c,0,b),h.Zb.onaudioprocess=function(d){var e=d.outputBuffer.length,f=Xc(e);if(f)for(var g=d.outputBuffer.numberOfChannels,k=0;k<g;k++)for(var p=d.outputBuffer.getChannelData(k),r=0;r<e;r++)p[r]=C[(f>>2)+(g*r+k)]},h.Zb.connect(h.Qb.destination),a=function(){h.Qb&&"suspended"===h.Qb.state&&h.Qb.resume()},document.addEventListener("click",
a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ua:function(){return h.Qb?h.Qb.sampleRate:0},B:function(){null!==h.Qb&&(h.Zb&&h.Zb.disconnect(),h.Qb.close(),h.Qb=null,h.Zb=null)},A:function(){return navigator.userAgent.includes("Macintosh")?1:0},s:function(){return performance.now()},tb:function(a){var b=Date.now()/1E3|0;a&&(B[a>>2]=b);return b}};
(function(){function a(e){h.asm=e.exports;ia=h.asm.ub;ta=e=ia.buffer;h.HEAP8=x=new Int8Array(e);h.HEAP16=ua=new Int16Array(e);h.HEAP32=B=new Int32Array(e);h.HEAPU8=v=new Uint8Array(e);h.HEAPU16=va=new Uint16Array(e);h.HEAPU32=wa=new Uint32Array(e);h.HEAPF32=C=new Float32Array(e);h.HEAPF64=D=new Float64Array(e);xa=h.asm.xb;za.unshift(h.asm.vb);E--;h.monitorRunDependencies&&h.monitorRunDependencies(E);0==E&&(null!==Ea&&(clearInterval(Ea),Ea=null),Fa&&(e=Fa,Fa=null,e()))}function b(e){a(e.instance)}
function c(e){return Ja().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){m("failed to asynchronously prepare wasm: "+f);n(f)})}var d={a:Yc};E++;h.monitorRunDependencies&&h.monitorRunDependencies(E);if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return m("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ha||"function"!==typeof WebAssembly.instantiateStreaming||Ga()||"function"!==typeof fetch?c(b):fetch(F,
{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){m("wasm streaming compile failed: "+f);m("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.vb).apply(null,arguments)};
var A=h._malloc=function(){return(A=h._malloc=h.asm.wb).apply(null,arguments)},Vc=h.__sapp_emsc_notify_keyboard_hidden=function(){return(Vc=h.__sapp_emsc_notify_keyboard_hidden=h.asm.yb).apply(null,arguments)};h.__sapp_emsc_onpaste=function(){return(h.__sapp_emsc_onpaste=h.asm.zb).apply(null,arguments)};
var Sc=h.__sapp_html5_get_ask_leave_site=function(){return(Sc=h.__sapp_html5_get_ask_leave_site=h.asm.Ab).apply(null,arguments)},Tc=h.__sapp_emsc_begin_drop=function(){return(Tc=h.__sapp_emsc_begin_drop=h.asm.Bb).apply(null,arguments)};h.__sapp_emsc_drop=function(){return(h.__sapp_emsc_drop=h.asm.Cb).apply(null,arguments)};
var Uc=h.__sapp_emsc_end_drop=function(){return(Uc=h.__sapp_emsc_end_drop=h.asm.Db).apply(null,arguments)},Wc=h.__sapp_emsc_invoke_fetch_cb=function(){return(Wc=h.__sapp_emsc_invoke_fetch_cb=h.asm.Eb).apply(null,arguments)};h._main=function(){return(h._main=h.asm.Fb).apply(null,arguments)};
var Xc=h.__saudio_emsc_pull=function(){return(Xc=h.__saudio_emsc_pull=h.asm.Gb).apply(null,arguments)},Rc=h.___errno_location=function(){return(Rc=h.___errno_location=h.asm.Hb).apply(null,arguments)},ma=h.stackSave=function(){return(ma=h.stackSave=h.asm.Ib).apply(null,arguments)},oa=h.stackRestore=function(){return(oa=h.stackRestore=h.asm.Jb).apply(null,arguments)},la=h.stackAlloc=function(){return(la=h.stackAlloc=h.asm.Kb).apply(null,arguments)},Zc;
function $c(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Fa=function ad(){Zc||bd();Zc||(Fa=ad)};
function bd(a){function b(){if(!Zc&&(Zc=!0,h.calledRun=!0,!ja)){h.noFSInit||Lb||(Lb=!0,Kb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Ob("stdin",h.stdin):Fb("/dev/tty","/dev/stdin"),h.stdout?Ob("stdout",null,h.stdout):Fb("/dev/tty","/dev/stdout"),h.stderr?Ob("stderr",null,h.stderr):Fb("/dev/tty1","/dev/stderr"),P("/dev/stdin",0),P("/dev/stdout",1),P("/dev/stderr",1));nb=!1;Pa(za);Pa(Aa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(cd){var c=a,d=h._main;c=c||[];var e=c.length+
1,f=la(4*(e+1));B[f>>2]=sa(da);for(var g=1;g<e;g++)B[(f>>2)+g]=sa(c[g-1]);B[(f>>2)+e]=0;try{var k=d(e,f);if(!noExitRuntime){if(h.onExit)h.onExit(k);ja=!0}ea(k,new $c(k))}catch(p){p instanceof $c||"unwind"==p||ea(1,p)}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)c=h.postRun.shift(),Ca.unshift(c);Pa(Ca)}}a=a||ca;if(!(0<E)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Da();Pa(ya);0<E||(h.setStatus?(h.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=bd;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var cd=!0;h.noInitialRun&&(cd=!1);bd();
