
var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign,ba=aa({},h),ca=[],da="./this.program",ea=(a,b)=>{throw b;},l="";"undefined"!==typeof document&&document.currentScript&&(l=document.currentScript.src);l=0!==l.indexOf("blob:")?l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var fa=h.print||console.log.bind(console),m=h.printErr||console.warn.bind(console);aa(h,ba);ba=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);
h.quit&&(ea=h.quit);var ha;h.wasmBinary&&(ha=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!==typeof WebAssembly&&n("no native wasm support detected");var ia,ja=!1;
function ka(a,b,c){var d={string:function(p){var r=0;if(null!==p&&void 0!==p&&0!==p){var q=(p.length<<2)+1;r=la(q);u(p,v,r,q)}return r},array:function(p){var r=la(p.length);x.set(p,r);return r}};a=h["_"+a];var e=[],f=0;if(c)for(var g=0;g<c.length;g++){var k=d[b[g]];k?(0===f&&(f=ma()),e[g]=k(c[g])):e[g]=c[g]}b=a.apply(null,e);b=function(p){0!==f&&na(f);return p}(b)}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&oa)return oa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function y(a,b){return a?qa(v,a,b):""}
function u(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function z(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ra(a){var b=z(a)+1,c=A(b);c&&u(a,x,c,b);return c}function sa(a){var b=z(a)+1,c=la(b);u(a,x,c,b);return c}var ta,x,v,ua,va,B,wa,C,D,xa,ya=[],za=[],Aa=[],Ba=[],Ca=[];function Da(){var a=h.preRun.shift();ya.unshift(a)}var E=0,Ea=null,Fa=null;h.preloadedImages={};h.preloadedAudios={};
function n(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";m(a);ja=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ga(){return F.startsWith("data:application/octet-stream;base64,")}var F;F="SkyBoy.wasm";if(!Ga()){var Ha=F;F=h.locateFile?h.locateFile(Ha,l):l+Ha}function Ia(){var a=F;try{if(a==F&&ha)return new Uint8Array(ha);throw"both async and sync fetching of the wasm failed";}catch(b){n(b)}}
function Ja(){return ha||"function"!==typeof fetch?Promise.resolve().then(function(){return Ia()}):fetch(F,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+F+"'";return a.arrayBuffer()}).catch(function(){return Ia()})}
var G,Ka,Oa={153112:function(){document.getElementById("fileInput").style.visibility="hidden"},153200:function(a,b,c,d){var e=document.getElementById("fileInput");e.style.left=a+"px";e.style.top=b+"px";e.style.width=c+"px";e.style.height=d+"px";e.style.visibility="visible";if(""!=e.value){console.log(e.value);var f=new FileReader;a=e.files[0];f.addEventListener("loadend",function(){const k=new Uint8Array(f.result);var p="/offline/"+g;La(p,k);Ma(function(){});document.getElementById("fileStaging").value=
p});f.readAsArrayBuffer(a);var g=a.name;e.value=""}a=document.getElementById("fileStaging");e="";""!=a.value&&(e=a.value,a.value="");a=z(e)+1;b=A(a);u(e,v,b,a);return b},154224:function(){Ma(function(){})},154254:function(){Ma(function(){})},154284:function(){H("/offline");Na(I,"/offline");Ma(!0,function(){})}};function Pa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.Pd;"number"===typeof c?void 0===b.Bc?J(c)():J(c)(b.Bc):c(void 0===b.Bc?null:b.Bc)}}}var Qa=[];
function J(a){var b=Qa[a];b||(a>=Qa.length&&(Qa.length=a+1),Qa[a]=b=xa.get(a));return b}function Ra(){function a(g){return(g=g.toTimeString().match(/\(([A-Za-z ]+)\)$/))?g[1]:"GMT"}var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);B[Sa()>>2]=60*f;B[Ta()>>2]=Number(b!=e);c=a(c);d=a(d);c=ra(c);d=ra(d);e<b?(B[K()>>2]=c,B[K()+4>>2]=d):(B[K()>>2]=d,B[K()+4>>2]=c)}var Ua;
function Va(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Wa(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Va(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Xa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ya(a){if("/"===a)return"/";a=Wa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Za(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){n("randomDevice")}}
function $a(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Va(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var ab=[];function bb(a,b){ab[a]={input:[],Tb:[],kc:b};cb(a,db)}
var db={open:function(a){var b=ab[a.node.vc];if(!b)throw new L(43);a.Rb=b;a.seekable=!1},close:function(a){a.Rb.kc.flush(a.Rb)},flush:function(a){a.Rb.kc.flush(a.Rb)},read:function(a,b,c,d){if(!a.Rb||!a.Rb.kc.Tc)throw new L(60);for(var e=0,f=0;f<d;f++){try{var g=a.Rb.kc.Tc(a.Rb)}catch(k){throw new L(29);}if(void 0===g&&0===e)throw new L(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Rb||!a.Rb.kc.Ec)throw new L(60);try{for(var e=
0;e<d;e++)a.Rb.kc.Ec(a.Rb,b[c+e])}catch(f){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},eb={Tc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;var c=Array(z(b)+1);b=u(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},Ec:function(a,b){null===b||10===b?(fa(qa(a.Tb,0)),a.Tb=[]):0!=b&&a.Tb.push(b)},
flush:function(a){a.Tb&&0<a.Tb.length&&(fa(qa(a.Tb,0)),a.Tb=[])}},fb={Ec:function(a,b){null===b||10===b?(m(qa(a.Tb,0)),a.Tb=[]):0!=b&&a.Tb.push(b)},flush:function(a){a.Tb&&0<a.Tb.length&&(m(qa(a.Tb,0)),a.Tb=[])}},M={Yb:null,Vb:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.Yb||(M.Yb={dir:{node:{Xb:M.Nb.Xb,Ub:M.Nb.Ub,lc:M.Nb.lc,uc:M.Nb.uc,Zc:M.Nb.Zc,zc:M.Nb.zc,xc:M.Nb.xc,wc:M.Nb.wc,yc:M.Nb.yc},stream:{fc:M.Pb.fc}},
file:{node:{Xb:M.Nb.Xb,Ub:M.Nb.Ub},stream:{fc:M.Pb.fc,read:M.Pb.read,write:M.Pb.write,Lc:M.Pb.Lc,Vc:M.Pb.Vc,Xc:M.Pb.Xc}},link:{node:{Xb:M.Nb.Xb,Ub:M.Nb.Ub,nc:M.Nb.nc},stream:{}},Nc:{node:{Xb:M.Nb.Xb,Ub:M.Nb.Ub},stream:gb}});c=hb(a,b,c,d);N(c.mode)?(c.Nb=M.Yb.dir.node,c.Pb=M.Yb.dir.stream,c.Ob={}):32768===(c.mode&61440)?(c.Nb=M.Yb.file.node,c.Pb=M.Yb.file.stream,c.Qb=0,c.Ob=null):40960===(c.mode&61440)?(c.Nb=M.Yb.link.node,c.Pb=M.Yb.link.stream):8192===(c.mode&61440)&&(c.Nb=M.Yb.Nc.node,c.Pb=M.Yb.Nc.stream);
c.timestamp=Date.now();a&&(a.Ob[b]=c,a.timestamp=c.timestamp);return c},qd:function(a){return a.Ob?a.Ob.subarray?a.Ob.subarray(0,a.Qb):new Uint8Array(a.Ob):new Uint8Array(0)},Qc:function(a,b){var c=a.Ob?a.Ob.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ob,a.Ob=new Uint8Array(b),0<a.Qb&&a.Ob.set(c.subarray(0,a.Qb),0))},Bd:function(a,b){if(a.Qb!=b)if(0==b)a.Ob=null,a.Qb=0;else{var c=a.Ob;a.Ob=new Uint8Array(b);c&&a.Ob.set(c.subarray(0,Math.min(b,a.Qb)));a.Qb=
b}},Nb:{Xb:function(a){var b={};b.Nd=8192===(a.mode&61440)?a.id:1;b.Sd=a.id;b.mode=a.mode;b.Vd=1;b.uid=0;b.Qd=0;b.vc=a.vc;N(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Qb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Jd=new Date(a.timestamp);b.Dc=new Date(a.timestamp);b.Ld=new Date(a.timestamp);b.kd=4096;b.Kd=Math.ceil(b.size/b.kd);return b},Ub:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.Bd(a,b.size)},lc:function(){throw ib[44];
},uc:function(a,b,c,d){return M.createNode(a,b,c,d)},Zc:function(a,b,c){if(N(a.mode)){try{var d=O(b,c)}catch(f){}if(d)for(var e in d.Ob)throw new L(55);}delete a.parent.Ob[a.name];a.parent.timestamp=Date.now();a.name=c;b.Ob[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},zc:function(a,b){delete a.Ob[b];a.timestamp=Date.now()},xc:function(a,b){var c=O(a,b),d;for(d in c.Ob)throw new L(55);delete a.Ob[b];a.timestamp=Date.now()},wc:function(a){var b=[".",".."],c;for(c in a.Ob)a.Ob.hasOwnProperty(c)&&
b.push(c);return b},yc:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},nc:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},Pb:{read:function(a,b,c,d,e){var f=a.node.Ob;if(e>=a.node.Qb)return 0;a=Math.min(a.node.Qb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ob||a.Ob.subarray)){if(f)return a.Ob=b.subarray(c,c+d),a.Qb=d;
if(0===a.Qb&&0===e)return a.Ob=b.slice(c,c+d),a.Qb=d;if(e+d<=a.Qb)return a.Ob.set(b.subarray(c,c+d),e),d}M.Qc(a,e+d);if(a.Ob.subarray&&b.subarray)a.Ob.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ob[e+f]=b[c+f];a.Qb=Math.max(a.Qb,e+d);return d},fc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Qb);if(0>b)throw new L(28);return b},Lc:function(a,b,c){M.Qc(a.node,b+c);a.node.Qb=Math.max(a.node.Qb,b+c)},Vc:function(a,b,c,d,e,f){if(0!==b)throw new L(28);if(32768!==
(a.node.mode&61440))throw new L(43);a=a.node.Ob;if(f&2||a.buffer!==ta){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;n();c=void 0;if(!c)throw new L(48);x.set(a,c)}else d=!1,c=a.byteOffset;return{Yd:c,Hd:d}},Xc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);if(e&2)return 0;M.Pb.write(a,b,0,d,c,!1);return 0}}},I={Oc:{},indexedDB:function(){if("undefined"!==typeof indexedDB)return indexedDB;var a=null;"object"===typeof window&&(a=window.indexedDB||
window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB);a||n("IDBFS used, but indexedDB not supported");return a},jd:21,ec:"FILE_DATA",Vb:function(a){return M.Vb.apply(null,arguments)},fd:function(a,b,c){I.rd(a,function(d,e){if(d)return c(d);I.sd(a,function(f,g){if(f)return c(f);I.yd(b?g:e,b?e:g,c)})})},pd:function(a,b){var c=I.Oc[a];if(c)return b(null,c);try{var d=I.indexedDB().open(a,I.jd)}catch(e){return b(e)}if(!d)return b("Unable to connect to IndexedDB");d.onupgradeneeded=function(e){var f=
e.target.result;e=e.target.transaction;f=f.objectStoreNames.contains(I.ec)?e.objectStore(I.ec):f.createObjectStore(I.ec);f.indexNames.contains("timestamp")||f.createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=function(){c=d.result;I.Oc[a]=c;b(null,c)};d.onerror=function(e){b(this.error);e.preventDefault()}},rd:function(a,b){function c(k){return"."!==k&&".."!==k}function d(k){return function(p){return Wa(k+"/"+p)}}var e={};for(a=jb(a.mc).filter(c).map(d(a.mc));a.length;){var f=a.pop();
try{var g=kb(f)}catch(k){return b(k)}N(g.mode)&&a.push.apply(a,jb(f).filter(c).map(d(f)));e[f]={timestamp:g.Dc}}return b(null,{type:"local",entries:e})},sd:function(a,b){var c={};I.pd(a.mc,function(d,e){if(d)return b(d);try{var f=e.transaction([I.ec],"readonly");f.onerror=function(g){b(this.error);g.preventDefault()};f.objectStore(I.ec).index("timestamp").openKeyCursor().onsuccess=function(g){g=g.target.result;if(!g)return b(null,{type:"remote",db:e,entries:c});c[g.primaryKey]={timestamp:g.key};g.continue()}}catch(g){return b(g)}})},
vd:function(a,b){try{var c=P(a).node;var d=kb(a)}catch(e){return b(e)}return N(d.mode)?b(null,{timestamp:d.Dc,mode:d.mode}):32768===(d.mode&61440)?(c.Ob=M.qd(c),b(null,{timestamp:d.Dc,mode:d.mode,contents:c.Ob})):b(Error("node type not supported"))},Dd:function(a,b,c){try{if(N(b.mode))for(var d=b.mode,e=a.split("/"),f="",g=0;g<e.length;++g){if(e[g]){f+="/"+e[g];try{H(f,d)}catch(w){if(20!=w.Zb)throw w;}}}else if(32768===(b.mode&61440))La(a,b.contents,{Mc:!0});else return c(Error("node type not supported"));
var k=b.mode;var p="string"===typeof a?P(a,{hc:!0}).node:a;if(!p.Nb.Ub)throw new L(63);p.Nb.Ub(p,{mode:k&4095|p.mode&-4096,timestamp:Date.now()});var r=b.timestamp,q=b.timestamp,t=P(a,{hc:!0}).node;t.Nb.Ub(t,{timestamp:Math.max(r,q)})}catch(w){return c(w)}c(null)},zd:function(a,b){try{P(a);var c=kb(a);if(N(c.mode)){var d=P(a,{parent:!0}).node,e=Ya(a),f=O(d,e),g=lb(d,e,!0);if(g)throw new L(g);if(!d.Nb.xc)throw new L(63);if(f.ic)throw new L(10);d.Nb.xc(d,e);mb(f)}else if(32768===(c.mode&61440)){var k=
P(a,{parent:!0}).node;if(!k)throw new L(44);var p=Ya(a),r=O(k,p),q=lb(k,p,!1);if(q)throw new L(q);if(!k.Nb.zc)throw new L(63);if(r.ic)throw new L(10);k.Nb.zc(k,p);mb(r)}}catch(t){return b(t)}b(null)},wd:function(a,b,c){a=a.get(b);a.onsuccess=function(d){c(null,d.target.result)};a.onerror=function(d){c(this.error);d.preventDefault()}},Ed:function(a,b,c,d){try{var e=a.put(c,b)}catch(f){d(f);return}e.onsuccess=function(){d(null)};e.onerror=function(f){d(this.error);f.preventDefault()}},Ad:function(a,
b,c){a=a.delete(b);a.onsuccess=function(){c(null)};a.onerror=function(d){c(this.error);d.preventDefault()}},yd:function(a,b,c){function d(q){if(q&&!k)return k=!0,c(q)}var e=0,f=[];Object.keys(a.entries).forEach(function(q){var t=a.entries[q],w=b.entries[q];w&&t.timestamp.getTime()==w.timestamp.getTime()||(f.push(q),e++)});var g=[];Object.keys(b.entries).forEach(function(q){a.entries[q]||(g.push(q),e++)});if(!e)return c(null);var k=!1,p=("remote"===a.type?a.db:b.db).transaction([I.ec],"readwrite"),
r=p.objectStore(I.ec);p.onerror=function(q){d(this.error);q.preventDefault()};p.oncomplete=function(){k||c(null)};f.sort().forEach(function(q){"local"===b.type?I.wd(r,q,function(t,w){if(t)return d(t);I.Dd(q,w,d)}):I.vd(q,function(t,w){if(t)return d(t);I.Ed(r,q,w,d)})});g.sort().reverse().forEach(function(q){"local"===b.type?I.zd(q,d):I.Ad(r,q,d)})}},nb=null,ob={},rb=[],sb=1,Q=null,tb=!0,L=null,ib={},ub=0;
function P(a,b){a=$a("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Rc:!0,Fc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Fc)throw new L(32);a=Va(a.split("/").filter(function(g){return!!g}),!1);var e=nb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=O(e,a[d]);c=Wa(c+"/"+a[d]);e.ic&&(!f||f&&b.Rc)&&(e=e.ic.root);if(!f||b.hc)for(f=0;40960===(e.mode&61440);)if(e=vb(c),c=$a(Xa(c),e),e=P(c,{Fc:b.Fc}).node,40<f++)throw new L(32);}return{path:c,node:e}}
function wb(a){for(var b;;){if(a===a.parent)return a=a.Vb.mc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function xb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Q.length}function mb(a){var b=xb(a.parent.id,a.name);if(Q[b]===a)Q[b]=a.jc;else for(b=Q[b];b;){if(b.jc===a){b.jc=a.jc;break}b=b.jc}}
function O(a,b){var c;if(c=(c=yb(a,"x"))?c:a.Nb.lc?0:2)throw new L(c,a);for(c=Q[xb(a.id,b)];c;c=c.jc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Nb.lc(a,b)}function hb(a,b,c,d){a=new zb(a,b,c,d);b=xb(a.parent.id,a.name);a.jc=Q[b];return Q[b]=a}function N(a){return 16384===(a&61440)}var Ab={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Bb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function yb(a,b){if(tb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Cb(a,b){try{return O(a,b),20}catch(c){}return yb(a,"wx")}function lb(a,b,c){try{var d=O(a,b)}catch(e){return e.Zb}if(a=yb(a,"wx"))return a;if(c){if(!N(d.mode))return 54;if(d===d.parent||"/"===wb(d))return 10}else if(N(d.mode))return 31;return 0}function Db(a){var b=4096;for(a=a||0;a<=b;a++)if(!rb[a])return a;throw new L(33);}
function Eb(a,b){Fb||(Fb=function(){},Fb.prototype={});var c=new Fb,d;for(d in a)c[d]=a[d];a=c;b=Db(b);a.cc=b;return rb[b]=a}var gb={open:function(a){a.Pb=ob[a.node.vc].Pb;a.Pb.open&&a.Pb.open(a)},fc:function(){throw new L(70);}};function cb(a,b){ob[a]={Pb:b}}function Gb(){for(var a=[],b=[nb.Vb];b.length;){var c=b.pop();a.push(c);b.push.apply(b,c.Wc)}return a}
function Ma(a,b){function c(g){ub--;return b(g)}function d(g){if(g){if(!d.md)return d.md=!0,c(g)}else++f>=e.length&&c(null)}"function"===typeof a&&(b=a,a=!1);ub++;1<ub&&m("warning: "+ub+" FS.syncfs operations in flight at once, probably just doing extra work");var e=Gb(),f=0;e.forEach(function(g){if(!g.type.fd)return d(null);g.type.fd(g,a,d)})}
function Na(a,b){var c="/"===b,d=!b;if(c&&nb)throw new L(10);if(!c&&!d){var e=P(b,{Rc:!1});b=e.path;e=e.node;if(e.ic)throw new L(10);if(!N(e.mode))throw new L(54);}b={type:a,Wd:{},mc:b,Wc:[]};a=a.Vb(b);a.Vb=b;b.root=a;c?nb=a:e&&(e.ic=b,e.Vb&&e.Vb.Wc.push(b))}function Hb(a,b,c){var d=P(a,{parent:!0}).node;a=Ya(a);if(!a||"."===a||".."===a)throw new L(28);var e=Cb(d,a);if(e)throw new L(e);if(!d.Nb.uc)throw new L(63);return d.Nb.uc(d,a,b,c)}
function H(a,b){return Hb(a,(void 0!==b?b:511)&1023|16384,0)}function Ib(a,b,c){"undefined"===typeof c&&(c=b,b=438);Hb(a,b|8192,c)}function Jb(a,b){if(!$a(a))throw new L(44);var c=P(b,{parent:!0}).node;if(!c)throw new L(44);b=Ya(b);var d=Cb(c,b);if(d)throw new L(d);if(!c.Nb.yc)throw new L(63);c.Nb.yc(c,b,a)}function jb(a){a=P(a,{hc:!0}).node;if(!a.Nb.wc)throw new L(54);return a.Nb.wc(a)}
function vb(a){a=P(a).node;if(!a)throw new L(44);if(!a.Nb.nc)throw new L(28);return $a(wb(a.parent),a.Nb.nc(a))}function kb(a){a=P(a,{hc:!0}).node;if(!a)throw new L(44);if(!a.Nb.Xb)throw new L(63);return a.Nb.Xb(a)}
function R(a,b,c,d){if(""===a)throw new L(44);if("string"===typeof b){var e=Ab[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Wa(a);try{f=P(a,{hc:!(b&131072)}).node}catch(g){}}e=!1;if(b&64)if(f){if(b&128)throw new L(20);}else f=Hb(a,c,0),e=!0;if(!f)throw new L(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!N(f.mode))throw new L(54);if(!e&&(c=f?40960===(f.mode&61440)?32:N(f.mode)&&
("r"!==Bb(b)||b&512)?31:yb(f,Bb(b)):44))throw new L(c);if(b&512){c=f;c="string"===typeof c?P(c,{hc:!0}).node:c;if(!c.Nb.Ub)throw new L(63);if(N(c.mode))throw new L(31);if(32768!==(c.mode&61440))throw new L(28);if(e=yb(c,"w"))throw new L(e);c.Nb.Ub(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Eb({node:f,path:wb(f),id:f.id,flags:b,mode:f.mode,seekable:!0,position:0,Pb:f.Pb,Nb:f.Nb,Fd:[],error:!1},d);d.Pb.open&&d.Pb.open(d);!h.logReadFiles||b&1||(Kb||(Kb={}),a in Kb||(Kb[a]=1));return d}
function Lb(a){if(null===a.cc)throw new L(8);a.Cc&&(a.Cc=null);try{a.Pb.close&&a.Pb.close(a)}catch(b){throw b;}finally{rb[a.cc]=null}a.cc=null}function Mb(a,b,c){if(null===a.cc)throw new L(8);if(!a.seekable||!a.Pb.fc)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.Pb.fc(a,b,c);a.Fd=[]}
function Nb(a,b,c,d,e){var f=void 0;if(0>d||0>f)throw new L(28);if(null===a.cc)throw new L(8);if(0===(a.flags&2097155))throw new L(8);if(N(a.node.mode))throw new L(31);if(!a.Pb.write)throw new L(28);a.seekable&&a.flags&1024&&Mb(a,0,2);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new L(70);b=a.Pb.write(a,b,c,d,f,e);g||(a.position+=b);return b}
function La(a,b,c){c=c||{};c.flags=c.flags||577;a=R(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(z(b)+1);b=u(b,d,0,d.length);Nb(a,d,0,b,c.Mc)}else if(ArrayBuffer.isView(b))Nb(a,b,0,b.byteLength,c.Mc);else throw Error("Unsupported data type");Lb(a)}
function Ob(){L||(L=function(a,b){this.node=b;this.Cd=function(c){this.Zb=c};this.Cd(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(function(a){ib[a]=new L(a);ib[a].stack="<generic error, no stack>"}))}var Pb;function Qb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Rb(a,b,c){a=Wa("/dev/"+a);var d=Qb(!!b,!!c);Sb||(Sb=64);var e=Sb++<<8|0;cb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,g,k,p){for(var r=0,q=0;q<p;q++){try{var t=b()}catch(w){throw new L(29);}if(void 0===t&&0===r)throw new L(6);if(null===t||void 0===t)break;r++;g[k+q]=t}r&&(f.node.timestamp=Date.now());return r},write:function(f,g,k,p){for(var r=0;r<p;r++)try{c(g[k+r])}catch(q){throw new L(29);}p&&(f.node.timestamp=Date.now());return r}});
Ib(a,d,e)}var Sb,S={},Fb,Kb,Tb=void 0;function Ub(){Tb+=4;return B[Tb-4>>2]}function Vb(a){a=rb[a];if(!a)throw new L(8);return a}var Wb=[],Xb=0;function Yb(){for(var a=T.length-1;0<=a;--a)Zb(a);T=[];$b=[]}var $b=[];function ac(){if(Xb&&bc.qc)for(var a=0;a<$b.length;++a){var b=$b[a];$b.splice(a,1);--a;b.ae.apply(null,b.Id)}}var T=[];function Zb(a){var b=T[a];b.target.removeEventListener(b.Wb,b.nd,b.$b);T.splice(a,1)}
function U(a){function b(d){++Xb;bc=a;ac();a.dc(d);ac();--Xb}if(a.bc)a.nd=b,a.target.addEventListener(a.Wb,b,a.$b),T.push(a),cc||(Ba.push(Yb),cc=!0);else for(var c=0;c<T.length;++c)T[c].target==a.target&&T[c].Wb==a.Wb&&Zb(c--)}var cc,bc,dc,ec,fc,gc,hc,ic,jc=[0,document,window];function V(a){a=2<a?y(a):a;return jc[a]||document.querySelector(a)}function kc(a){return 0>jc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function lc(a,b,c,d,e,f){dc||(dc=A(176));a={target:V(a),qc:!0,Wb:f,bc:d,dc:function(g){var k=dc;D[k>>3]=g.timeStamp;var p=k>>2;B[p+2]=g.location;B[p+3]=g.ctrlKey;B[p+4]=g.shiftKey;B[p+5]=g.altKey;B[p+6]=g.metaKey;B[p+7]=g.repeat;B[p+8]=g.charCode;B[p+9]=g.keyCode;B[p+10]=g.which;u(g.key||"",v,k+44,32);u(g.code||"",v,k+76,32);u(g.char||"",v,k+108,32);u(g.locale||"",v,k+140,32);J(d)(e,k,b)&&g.preventDefault()},$b:c};U(a)}
function mc(a,b,c){D[a>>3]=b.timeStamp;a>>=2;B[a+2]=b.screenX;B[a+3]=b.screenY;B[a+4]=b.clientX;B[a+5]=b.clientY;B[a+6]=b.ctrlKey;B[a+7]=b.shiftKey;B[a+8]=b.altKey;B[a+9]=b.metaKey;ua[2*a+20]=b.button;ua[2*a+21]=b.buttons;B[a+11]=b.movementX;B[a+12]=b.movementY;c=kc(c);B[a+13]=b.clientX-c.left;B[a+14]=b.clientY-c.top}
function nc(a,b,c,d,e,f){ec||(ec=A(72));a=V(a);U({target:a,qc:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Wb:f,bc:d,dc:function(g){g=g||event;mc(ec,g,a);J(d)(e,ec,b)&&g.preventDefault()},$b:c})}
function oc(a,b,c,d,e){fc||(fc=A(260));U({target:a,Wb:e,bc:d,dc:function(f){f=f||event;var g=fc,k=document.pointerLockElement||document.Ic||document.Kc||document.Jc;B[g>>2]=!!k;var p=k&&k.id?k.id:"";u(k?k==window?"#window":k==screen?"#screen":k&&k.nodeName?k.nodeName:"":"",v,g+4,128);u(p,v,g+132,128);J(d)(20,g,b)&&f.preventDefault()},$b:c})}function pc(a,b,c,d,e){U({target:a,Wb:e,bc:d,dc:function(f){f=f||event;J(d)(38,0,b)&&f.preventDefault()},$b:c})}
function qc(a,b,c,d){gc||(gc=A(36));a=V(a);U({target:a,Wb:"resize",bc:d,dc:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=gc;B[g>>2]=e.detail;B[g+4>>2]=f.clientWidth;B[g+8>>2]=f.clientHeight;B[g+12>>2]=innerWidth;B[g+16>>2]=innerHeight;B[g+20>>2]=outerWidth;B[g+24>>2]=outerHeight;B[g+28>>2]=pageXOffset;B[g+32>>2]=pageYOffset;J(d)(10,g,b)&&e.preventDefault()}}},$b:c})}
function rc(a,b,c,d,e,f){hc||(hc=A(1696));a=V(a);U({target:a,qc:"touchstart"==f||"touchend"==f,Wb:f,bc:d,dc:function(g){for(var k,p={},r=g.touches,q=0;q<r.length;++q)k=r[q],k.Uc=k.Yc=0,p[k.identifier]=k;for(q=0;q<g.changedTouches.length;++q)k=g.changedTouches[q],k.Uc=1,p[k.identifier]=k;for(q=0;q<g.targetTouches.length;++q)p[g.targetTouches[q].identifier].Yc=1;r=hc;D[r>>3]=g.timeStamp;var t=r>>2;B[t+3]=g.ctrlKey;B[t+4]=g.shiftKey;B[t+5]=g.altKey;B[t+6]=g.metaKey;t+=7;var w=kc(a),pa=0;for(q in p)if(k=
p[q],B[t]=k.identifier,B[t+1]=k.screenX,B[t+2]=k.screenY,B[t+3]=k.clientX,B[t+4]=k.clientY,B[t+5]=k.pageX,B[t+6]=k.pageY,B[t+7]=k.Uc,B[t+8]=k.Yc,B[t+9]=k.clientX-w.left,B[t+10]=k.clientY-w.top,t+=13,31<++pa)break;B[r+8>>2]=pa;J(d)(e,r,b)&&g.preventDefault()},$b:c})}function sc(a,b,c,d,e,f){a={target:V(a),Wb:f,bc:d,dc:function(g){g=g||event;J(d)(e,0,b)&&g.preventDefault()},$b:c};U(a)}
function tc(a,b,c,d){ic||(ic=A(104));U({target:a,qc:!0,Wb:"wheel",bc:d,dc:function(e){e=e||event;var f=ic;mc(f,e,a);D[f+72>>3]=e.deltaX;D[f+80>>3]=e.deltaY;D[f+88>>3]=e.deltaZ;B[f+96>>2]=e.deltaMode;J(d)(9,f,b)&&e.preventDefault()},$b:c})}
function uc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function vc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function xc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function yc(a){a.Ud=a.getExtension("WEBGL_multi_draw")}
var zc=1,Ac=[],W=[],Bc=[],Cc=[],Dc=[],X=[],Ec=[],Fc={};function Y(a){Gc||(Gc=a)}function Hc(a){for(var b=zc++,c=a.length;c<b;c++)a[c]=null;return b}function Ic(a,b){a.Sc||(a.Sc=a.getContext,a.getContext=function(d,e){e=a.Sc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Jc(c,b):0}function Jc(a,b){var c=Hc(Ec),d={Rd:c,attributes:b,version:b.xd,Ac:a};a.canvas&&(a.canvas.Gd=d);Ec[c]=d;("undefined"===typeof b.Pc||b.Pc)&&Kc(d);return c}
function Kc(a){a||(a=Lc);if(!a.td){a.td=!0;var b=a.Ac;uc(b);vc(b);xc(b);b.Od=b.getExtension("EXT_disjoint_timer_query");yc(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Gc,Lc,Mc=["default","low-power","high-performance"];function Nc(a,b,c,d){for(var e=0;e<a;e++){var f=Z[c](),g=f&&Hc(d);f?(f.name=g,d[g]=f):Y(1282);B[b+4*e>>2]=g}}
function Oc(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)B[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Y(1280);m("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:Y(1280);m("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}B[b>>2]=c}else Y(1281)}function Pc(a){var b=z(a)+1,c=A(b);u(a,v,c,b);return c}
function Qc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Rc(a){var b=Z.ld;if(b){var c=b.pc[a];"number"===typeof c&&(b.pc[a]=c=Z.getUniformLocation(b,b.gd[a]+(0<c?"["+c+"]":"")));return c}Y(1282)}var Sc=[];function zb(a,b,c,d){a||(a=this);this.parent=a;this.Vb=a.Vb;this.ic=null;this.id=sb++;this.name=b;this.mode=c;this.Nb={};this.Pb={};this.vc=d}
Object.defineProperties(zb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Ob();Q=Array(4096);Na(M,"/");H("/tmp");H("/home");H("/home/web_user");
(function(){H("/dev");cb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Ib("/dev/null",259);bb(1280,eb);bb(1536,fb);Ib("/dev/tty",1280);Ib("/dev/tty1",1536);var a=Za();Rb("random",a);Rb("urandom",a);H("/dev/shm");H("/dev/shm/tmp")})();
(function(){H("/proc");var a=H("/proc/self");H("/proc/self/fd");Na({Vb:function(){var b=hb(a,"fd",16895,73);b.Nb={lc:function(c,d){var e=rb[+d];if(!e)throw new L(8);c={parent:null,Vb:{mc:"fake"},Nb:{nc:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();for(var Z,Tc=new Float32Array(288),Uc=0;288>Uc;++Uc)Sc[Uc]=Tc.subarray(0,Uc+1);
var bd={bb:function(a,b){Ua||(Ua=!0,Ra());a=new Date(1E3*B[a>>2]);B[b>>2]=a.getSeconds();B[b+4>>2]=a.getMinutes();B[b+8>>2]=a.getHours();B[b+12>>2]=a.getDate();B[b+16>>2]=a.getMonth();B[b+20>>2]=a.getFullYear()-1900;B[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);B[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;B[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;B[b+32>>2]=a;
a=B[K()+(a?4:0)>>2];B[b+40>>2]=a;return b},pa:function(a,b,c){Tb=c;try{var d=Vb(a);switch(b){case 0:var e=Ub();return 0>e?-28:R(d.path,d.flags,0,e).cc;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ub(),d.flags|=e,0;case 5:return e=Ub(),ua[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return B[Vc()>>2]=28,-1;default:return-28}}catch(f){if("undefined"===typeof S||!(f instanceof L))throw f;return-f.Zb}},eb:function(a,b,c){Tb=c;try{var d=Vb(a);switch(b){case 21509:case 21505:return d.Rb?
0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Rb?0:-59;case 21519:if(!d.Rb)return-59;var e=Ub();return B[e>>2]=0;case 21520:return d.Rb?-28:-59;case 21531:a=e=Ub();if(!d.Pb.ud)throw new L(59);return d.Pb.ud(d,b,a);case 21523:return d.Rb?0:-59;case 21524:return d.Rb?0:-59;default:n("bad ioctl syscall "+b)}}catch(f){if("undefined"===typeof S||!(f instanceof L))throw f;return-f.Zb}},fb:function(a,b,c){Tb=c;try{var d=y(a),e=c?Ub():0;return R(d,b,e).cc}catch(f){if("undefined"===
typeof S||!(f instanceof L))throw f;return-f.Zb}},k:function(a,b,c){Wb.length=0;var d;for(c>>=2;d=v[b++];)(d=105>d)&&c&1&&c++,Wb.push(d?D[c++>>1]:B[c]),++c;return Oa[a].apply(null,Wb)},X:function(){return devicePixelRatio},_:function(a,b,c){a=V(a);if(!a)return-4;a=kc(a);D[b>>3]=a.width;D[c>>3]=a.height;return 0},ab:function(a,b,c){v.copyWithin(a,b,b+c)},Wa:function(a,b){function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},y:function(){n("OOM")},U:function(a,b,c){a=V(a);
if(!a)return-4;a.width=b;a.height=c;return 0},ia:function(a,b,c,d){lc(a,b,c,d,2,"keydown");return 0},ga:function(a,b,c,d){lc(a,b,c,d,1,"keypress");return 0},ha:function(a,b,c,d){lc(a,b,c,d,3,"keyup");return 0},ra:function(a,b,c,d){nc(a,b,c,d,5,"mousedown");return 0},la:function(a,b,c,d){nc(a,b,c,d,33,"mouseenter");return 0},ka:function(a,b,c,d){nc(a,b,c,d,34,"mouseleave");return 0},ma:function(a,b,c,d){nc(a,b,c,d,8,"mousemove");return 0},oa:function(a,b,c,d){nc(a,b,c,d,6,"mouseup");return 0},ba:function(a,
b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Ic||document.body.Kc||document.body.Jc))return-1;a=V(a);if(!a)return-4;oc(a,b,c,d,"pointerlockchange");oc(a,b,c,d,"mozpointerlockchange");oc(a,b,c,d,"webkitpointerlockchange");oc(a,b,c,d,"mspointerlockchange");return 0},aa:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Ic||document.body.Kc||document.body.Jc))return-1;a=V(a);if(!a)return-4;pc(a,b,c,d,"pointerlockerror");pc(a,b,
c,d,"mozpointerlockerror");pc(a,b,c,d,"webkitpointerlockerror");pc(a,b,c,d,"mspointerlockerror");return 0},Sa:function(a,b,c,d){qc(a,b,c,d);return 0},ca:function(a,b,c,d){rc(a,b,c,d,25,"touchcancel");return 0},da:function(a,b,c,d){rc(a,b,c,d,23,"touchend");return 0},ea:function(a,b,c,d){rc(a,b,c,d,24,"touchmove");return 0},fa:function(a,b,c,d){rc(a,b,c,d,22,"touchstart");return 0},$:function(a,b,c,d){sc(a,b,c,d,31,"webglcontextlost");return 0},Z:function(a,b,c,d){sc(a,b,c,d,32,"webglcontextrestored");
return 0},ja:function(a,b,c,d){a=V(a);return"undefined"!==typeof a.onwheel?(tc(a,b,c,d),0):-1},L:function(a,b){b>>=2;b={alpha:!!B[b],depth:!!B[b+1],stencil:!!B[b+2],antialias:!!B[b+3],premultipliedAlpha:!!B[b+4],preserveDrawingBuffer:!!B[b+5],powerPreference:Mc[B[b+6]],failIfMajorPerformanceCaveat:!!B[b+7],xd:B[b+8],Td:B[b+9],Pc:B[b+10],od:B[b+11],Xd:B[b+12],Zd:B[b+13]};a=V(a);return!a||b.od?0:Ic(a,b)},rb:function(a,b){a=Ec[a];b=y(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==
b&&uc(Z);"OES_vertex_array_object"==b&&vc(Z);"WEBGL_draw_buffers"==b&&xc(Z);"WEBGL_multi_draw"==b&&yc(Z);return!!a.Ac.getExtension(b)},Fa:function(a){a>>=2;for(var b=0;14>b;++b)B[a+b]=0;B[a]=B[a+1]=B[a+3]=B[a+4]=B[a+8]=B[a+10]=1},ya:function(a){Lc=Ec[a];h.Md=Z=Lc&&Lc.Ac;return!a||Z?0:-5},na:function(a){try{var b=Vb(a);Lb(b);return 0}catch(c){if("undefined"===typeof S||!(c instanceof L))throw c;return c.Zb}},db:function(a,b,c,d){try{a:{for(var e=Vb(a),f=a=0;f<c;f++){var g=B[b+(8*f+4)>>2],k=e,p=B[b+
8*f>>2],r=g,q=void 0,t=x;if(0>r||0>q)throw new L(28);if(null===k.cc)throw new L(8);if(1===(k.flags&2097155))throw new L(8);if(N(k.node.mode))throw new L(31);if(!k.Pb.read)throw new L(28);var w="undefined"!==typeof q;if(!w)q=k.position;else if(!k.seekable)throw new L(70);var pa=k.Pb.read(k,t,p,r,q);w||(k.position+=pa);var pb=pa;if(0>pb){var wc=-1;break a}a+=pb;if(pb<g)break}wc=a}B[d>>2]=wc;return 0}catch(qb){if("undefined"===typeof S||!(qb instanceof L))throw qb;return qb.Zb}},$a:function(a,b,c,d,
e){try{var f=Vb(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Mb(f,a,d);Ka=[f.position>>>0,(G=f.position,1<=+Math.abs(G)?0<G?(Math.min(+Math.floor(G/4294967296),4294967295)|0)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];B[e>>2]=Ka[0];B[e+4>>2]=Ka[1];f.Cc&&0===a&&0===d&&(f.Cc=null);return 0}catch(g){if("undefined"===typeof S||!(g instanceof L))throw g;return g.Zb}},cb:function(a,b,c,d){try{a:{for(var e=Vb(a),f=a=0;f<c;f++){var g=Nb(e,x,B[b+8*f>>2],B[b+(8*
f+4)>>2]);if(0>g){var k=-1;break a}a+=g}k=a}B[d>>2]=k;return 0}catch(p){if("undefined"===typeof S||!(p instanceof L))throw p;return p.Zb}},b:function(a){Z.activeTexture(a)},W:function(a,b){Z.attachShader(W[a],X[b])},c:function(a,b){Z.bindBuffer(a,Ac[b])},S:function(a,b){Z.bindFramebuffer(a,Bc[b])},Oa:function(a,b){Z.bindRenderbuffer(a,Cc[b])},a:function(a,b){Z.bindTexture(a,Dc[b])},K:function(a,b,c,d){Z.blendColor(a,b,c,d)},M:function(a,b){Z.blendEquationSeparate(a,b)},N:function(a,b,c,d){Z.blendFuncSeparate(a,
b,c,d)},Qa:function(a,b,c,d){Z.bufferData(a,c?v.subarray(c,c+b):b,d)},o:function(a,b,c,d){Z.bufferSubData(a,b,v.subarray(d,d+c))},Ca:function(a){Z.clear(a)},Ea:function(a,b,c,d){Z.clearColor(a,b,c,d)},R:function(a){Z.clearDepth(a)},Da:function(a){Z.clearStencil(a)},i:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},hb:function(a){Z.compileShader(X[a])},La:function(a,b,c,d,e,f,g,k){Z.compressedTexImage2D(a,b,c,d,e,f,k?v.subarray(k,k+g):null)},Ja:function(){var a=Hc(W),b=Z.createProgram();b.name=a;b.tc=
b.rc=b.sc=0;b.Hc=1;W[a]=b;return a},jb:function(a){var b=Hc(X);X[b]=Z.createShader(a);return b},J:function(a){Z.cullFace(a)},nb:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Ac[d];e&&(Z.deleteBuffer(e),e.name=0,Ac[d]=null)}},h:function(a,b){for(var c=0;c<a;++c){var d=B[b+4*c>>2],e=Bc[d];e&&(Z.deleteFramebuffer(e),e.name=0,Bc[d]=null)}},x:function(a){if(a){var b=W[a];b?(Z.deleteProgram(b),b.name=0,W[a]=null):Y(1281)}},sa:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Cc[d];e&&(Z.deleteRenderbuffer(e),
e.name=0,Cc[d]=null)}},w:function(a){if(a){var b=X[a];b?(Z.deleteShader(b),X[a]=null):Y(1281)}},mb:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Dc[d];e&&(Z.deleteTexture(e),e.name=0,Dc[d]=null)}},u:function(a){Z.depthFunc(a)},v:function(a){Z.depthMask(!!a)},d:function(a){Z.disable(a)},H:function(a){Z.disableVertexAttribArray(a)},wa:function(a,b,c){Z.drawArrays(a,b,c)},xa:function(a,b,c,d){Z.drawElements(a,b,c,d)},e:function(a){Z.enable(a)},za:function(a){Z.enableVertexAttribArray(a)},I:function(a){Z.frontFace(a)},
Ra:function(a,b){Nc(a,b,"createBuffer",Ac)},Pa:function(a,b){Nc(a,b,"createRenderbuffer",Cc)},Ma:function(a,b){Nc(a,b,"createTexture",Dc)},Ga:function(a,b){return Z.getAttribLocation(W[a],y(b))},f:function(a,b){Oc(a,b)},Ha:function(a,b,c,d){a=Z.getProgramInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&d?u(a,v,d,b):0;c&&(B[c>>2]=b)},V:function(a,b,c){if(c)if(a>=zc)Y(1281);else if(a=W[a],35716==b)a=Z.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.tc)for(b=
0;b<Z.getProgramParameter(a,35718);++b)a.tc=Math.max(a.tc,Z.getActiveUniform(a,b).name.length+1);B[c>>2]=a.tc}else if(35722==b){if(!a.rc)for(b=0;b<Z.getProgramParameter(a,35721);++b)a.rc=Math.max(a.rc,Z.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.rc}else if(35381==b){if(!a.sc)for(b=0;b<Z.getProgramParameter(a,35382);++b)a.sc=Math.max(a.sc,Z.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.sc}else B[c>>2]=Z.getProgramParameter(a,b);else Y(1281)},gb:function(a,b,c,d){a=Z.getShaderInfoLog(X[a]);
null===a&&(a="(unknown error)");b=0<b&&d?u(a,v,d,b):0;c&&(B[c>>2]=b)},qa:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=Z.getShaderSource(X[a]),B[c>>2]=a?a.length+1:0):B[c>>2]=Z.getShaderParameter(X[a],b):Y(1281)},Ta:function(a){var b=Fc[a];if(!b){switch(a){case 7939:b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Pc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||
Y(1280);b=b&&Pc(b);break;case 7938:b=Pc("OpenGL ES 2.0 ("+Z.getParameter(7938)+")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Pc(b);break;default:Y(1280)}Fc[a]=b}return b},n:function(a,b){b=y(b);if(a=W[a]){var c=a,d=c.pc,e=c.hd,f;if(!d)for(c.pc=d={},c.gd={},f=0;f<Z.getProgramParameter(c,35718);++f){var g=Z.getActiveUniform(c,f);var k=g.name;g=g.size;var p=Qc(k);
p=0<p?k.slice(0,p):k;var r=c.Hc;c.Hc+=g;e[p]=[g,r];for(k=0;k<g;++k)d[r]=k,c.gd[r++]=p}c=a.pc;d=0;e=b;f=Qc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.hd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Z.getUniformLocation(a,b)))return d}else Y(1281);return-1},Ia:function(a){a=W[a];Z.linkProgram(a);a.pc=0;a.hd={}},Q:function(a,b){Z.polygonOffset(a,b)},Na:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},l:function(a,b,c,d){Z.scissor(a,b,c,d)},ib:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=
d?B[d+4*f>>2]:-1;e+=y(B[c+4*f>>2],0>g?void 0:g)}Z.shaderSource(X[a],e)},lb:function(a,b,c){Z.stencilFunc(a,b,c)},P:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},t:function(a){Z.stencilMask(a)},kb:function(a,b,c){Z.stencilOp(a,b,c)},O:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},Ka:function(a,b,c,d,e,f,g,k,p){var r=Z,q=r.texImage2D;if(p){var t=k-5120;t=1==t?v:4==t?B:6==t?C:5==t||28922==t?wa:va;var w=31-Math.clz32(t.BYTES_PER_ELEMENT);p=t.subarray(p>>w,p+e*(d*({5:3,6:4,8:2,29502:3,29504:4}[g-
6402]||1)*(1<<w)+4-1&-4)>>w)}else p=null;q.call(r,a,b,c,d,e,f,g,k,p)},g:function(a,b,c){Z.texParameteri(a,b,c)},G:function(a,b,c){if(288>=b)for(var d=Sc[b-1],e=0;e<b;++e)d[e]=C[c+4*e>>2];else d=C.subarray(c>>2,c+4*b>>2);Z.uniform1fv(Rc(a),d)},T:function(a,b){Z.uniform1i(Rc(a),b)},F:function(a,b,c){if(144>=b)for(var d=Sc[2*b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);Z.uniform2fv(Rc(a),d)},E:function(a,b,c){if(96>=b)for(var d=Sc[3*b-1],e=0;e<3*b;e+=3)d[e]=
C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2];else d=C.subarray(c>>2,c+12*b>>2);Z.uniform3fv(Rc(a),d)},D:function(a,b,c){if(72>=b){var d=Sc[4*b-1],e=C;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=C.subarray(c>>2,c+16*b>>2);Z.uniform4fv(Rc(a),d)},C:function(a,b,c,d){if(18>=b){var e=Sc[16*b-1],f=C;d>>=2;for(var g=0;g<16*b;g+=16){var k=d+g;e[g]=f[k];e[g+1]=f[k+1];e[g+2]=f[k+2];e[g+3]=f[k+3];e[g+4]=f[k+4];e[g+5]=f[k+5];e[g+6]=f[k+6];e[g+
7]=f[k+7];e[g+8]=f[k+8];e[g+9]=f[k+9];e[g+10]=f[k+10];e[g+11]=f[k+11];e[g+12]=f[k+12];e[g+13]=f[k+13];e[g+14]=f[k+14];e[g+15]=f[k+15]}}else e=C.subarray(d>>2,d+64*b>>2);Z.uniformMatrix4fv(Rc(a),!!c,e)},j:function(a){a=W[a];Z.useProgram(a);Z.ld=a},Aa:function(a,b){Z.vertexAttribDivisor(a,b)},Ba:function(a,b,c,d,e,f){Z.vertexAttribPointer(a,b,c,!!d,e,f)},m:function(a,b,c,d){Z.viewport(a,b,c,d)},Za:function(){h.$c=function(a){0!=Wc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",
h.$c)},Ya:function(){h.ed=function(a){a=a.clipboardData.getData("text");ka("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",h.ed)},Xa:function(a){h.$d=[];a=y(a);a=document.getElementById(a);h.ad=function(b){b.stopPropagation();b.preventDefault()};h.bd=function(b){b.stopPropagation();b.preventDefault()};h.cd=function(b){b.stopPropagation();b.preventDefault()};h.dd=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;h.Gc=c;Xc(c.length);var d;for(d=0;d<
c.length;d++)ka("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Yc(b.clientX,b.clientY)};a.addEventListener("dragenter",h.ad,!1);a.addEventListener("dragleave",h.bd,!1);a.addEventListener("dragover",h.cd,!1);a.addEventListener("drop",h.dd,!1)},r:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Zc()});document.body.append(a)},Y:function(a){return 0>a||a>=h.Gc.length?0:h.Gc[a].size},Ua:function(a,
b,c,d,e){var f=new FileReader;f.onload=function(g){g=g.target.result;g.byteLength>d?$c(a,0,1,b,0,c,d,e):(v.set(new Uint8Array(g),c),$c(a,1,0,b,g.byteLength,c,d,e))};f.onerror=function(){$c(a,0,2,b,0,c,d,e)};f.readAsArrayBuffer(h.Gc[a])},q:function(){document.getElementById("_sokol_app_input_element").focus()},_a:function(a){a=y(a);h.oc=document.getElementById(a);h.oc||console.log("sokol_app.h: invalid target:"+a);h.oc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+
a)},qb:function(){window.removeEventListener("beforeunload",h.$c)},pb:function(){window.removeEventListener("paste",h.ed)},ob:function(a){a=y(a);a=document.getElementById(a);a.removeEventListener("dragenter",h.ad);a.removeEventListener("dragleave",h.bd);a.removeEventListener("dragover",h.cd);a.removeEventListener("drop",h.dd)},z:function(){h.oc&&h.oc.requestPointerLock&&h.oc.requestPointerLock()},p:function(){document.getElementById("_sokol_app_input_element").blur()},Va:function(a){a=y(a);var b=
document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ta:function(){return h.ac?h.ac.bufferSize:0},va:function(a,b,c){h.Sb=null;h.ac=null;"undefined"!==typeof AudioContext?h.Sb=new AudioContext({sampleRate:a,
latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?h.Sb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(h.Sb=null,console.log("sokol_audio.h: no WebAudio support"));return h.Sb?(console.log("sokol_audio.h: sample rate ",h.Sb.sampleRate),h.ac=h.Sb.createScriptProcessor(c,0,b),h.ac.onaudioprocess=function(d){var e=d.outputBuffer.length,f=ad(e);if(f)for(var g=d.outputBuffer.numberOfChannels,k=0;k<g;k++)for(var p=d.outputBuffer.getChannelData(k),r=0;r<e;r++)p[r]=C[(f>>
2)+(g*r+k)]},h.ac.connect(h.Sb.destination),a=function(){h.Sb&&"suspended"===h.Sb.state&&h.Sb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ua:function(){return h.Sb?h.Sb.sampleRate:0},B:function(){null!==h.Sb&&(h.ac&&h.ac.disconnect(),h.Sb.close(),h.Sb=null,h.ac=null)},A:function(){return navigator.userAgent.includes("Macintosh")?1:0},s:function(){return performance.now()},sb:function(a){var b=
Date.now()/1E3|0;a&&(B[a>>2]=b);return b}};
(function(){function a(e){h.asm=e.exports;ia=h.asm.tb;ta=e=ia.buffer;h.HEAP8=x=new Int8Array(e);h.HEAP16=ua=new Int16Array(e);h.HEAP32=B=new Int32Array(e);h.HEAPU8=v=new Uint8Array(e);h.HEAPU16=va=new Uint16Array(e);h.HEAPU32=wa=new Uint32Array(e);h.HEAPF32=C=new Float32Array(e);h.HEAPF64=D=new Float64Array(e);xa=h.asm.wb;za.unshift(h.asm.ub);E--;h.monitorRunDependencies&&h.monitorRunDependencies(E);0==E&&(null!==Ea&&(clearInterval(Ea),Ea=null),Fa&&(e=Fa,Fa=null,e()))}function b(e){a(e.instance)}
function c(e){return Ja().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){m("failed to asynchronously prepare wasm: "+f);n(f)})}var d={a:bd};E++;h.monitorRunDependencies&&h.monitorRunDependencies(E);if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return m("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ha||"function"!==typeof WebAssembly.instantiateStreaming||Ga()||"function"!==typeof fetch?c(b):fetch(F,
{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){m("wasm streaming compile failed: "+f);m("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.ub).apply(null,arguments)};
var A=h._malloc=function(){return(A=h._malloc=h.asm.vb).apply(null,arguments)},Zc=h.__sapp_emsc_notify_keyboard_hidden=function(){return(Zc=h.__sapp_emsc_notify_keyboard_hidden=h.asm.xb).apply(null,arguments)};h.__sapp_emsc_onpaste=function(){return(h.__sapp_emsc_onpaste=h.asm.yb).apply(null,arguments)};
var Wc=h.__sapp_html5_get_ask_leave_site=function(){return(Wc=h.__sapp_html5_get_ask_leave_site=h.asm.zb).apply(null,arguments)},Xc=h.__sapp_emsc_begin_drop=function(){return(Xc=h.__sapp_emsc_begin_drop=h.asm.Ab).apply(null,arguments)};h.__sapp_emsc_drop=function(){return(h.__sapp_emsc_drop=h.asm.Bb).apply(null,arguments)};
var Yc=h.__sapp_emsc_end_drop=function(){return(Yc=h.__sapp_emsc_end_drop=h.asm.Cb).apply(null,arguments)},$c=h.__sapp_emsc_invoke_fetch_cb=function(){return($c=h.__sapp_emsc_invoke_fetch_cb=h.asm.Db).apply(null,arguments)};h._main=function(){return(h._main=h.asm.Eb).apply(null,arguments)};
var ad=h.__saudio_emsc_pull=function(){return(ad=h.__saudio_emsc_pull=h.asm.Fb).apply(null,arguments)},Vc=h.___errno_location=function(){return(Vc=h.___errno_location=h.asm.Gb).apply(null,arguments)},K=h.__get_tzname=function(){return(K=h.__get_tzname=h.asm.Hb).apply(null,arguments)},Ta=h.__get_daylight=function(){return(Ta=h.__get_daylight=h.asm.Ib).apply(null,arguments)},Sa=h.__get_timezone=function(){return(Sa=h.__get_timezone=h.asm.Jb).apply(null,arguments)},ma=h.stackSave=function(){return(ma=
h.stackSave=h.asm.Kb).apply(null,arguments)},na=h.stackRestore=function(){return(na=h.stackRestore=h.asm.Lb).apply(null,arguments)},la=h.stackAlloc=function(){return(la=h.stackAlloc=h.asm.Mb).apply(null,arguments)},cd;function dd(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Fa=function ed(){cd||fd();cd||(Fa=ed)};
function fd(a){function b(){if(!cd&&(cd=!0,h.calledRun=!0,!ja)){h.noFSInit||Pb||(Pb=!0,Ob(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Rb("stdin",h.stdin):Jb("/dev/tty","/dev/stdin"),h.stdout?Rb("stdout",null,h.stdout):Jb("/dev/tty","/dev/stdout"),h.stderr?Rb("stderr",null,h.stderr):Jb("/dev/tty1","/dev/stderr"),R("/dev/stdin",0),R("/dev/stdout",1),R("/dev/stderr",1));tb=!1;Pa(za);Pa(Aa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(gd){var c=a,d=h._main;c=c||[];var e=c.length+
1,f=la(4*(e+1));B[f>>2]=sa(da);for(var g=1;g<e;g++)B[(f>>2)+g]=sa(c[g-1]);B[(f>>2)+e]=0;try{var k=d(e,f);if(!noExitRuntime){if(h.onExit)h.onExit(k);ja=!0}ea(k,new dd(k))}catch(p){p instanceof dd||"unwind"==p||ea(1,p)}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)c=h.postRun.shift(),Ca.unshift(c);Pa(Ca)}}a=a||ca;if(!(0<E)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Da();Pa(ya);0<E||(h.setStatus?(h.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=fd;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var gd=!0;h.noInitialRun&&(gd=!1);fd();
