
var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign,ba=aa({},h),ca=[],da="./this.program",ea=(a,b)=>{throw b;},l="";"undefined"!==typeof document&&document.currentScript&&(l=document.currentScript.src);l=0!==l.indexOf("blob:")?l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var fa=h.print||console.log.bind(console),m=h.printErr||console.warn.bind(console);aa(h,ba);ba=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);
h.quit&&(ea=h.quit);var ha;h.wasmBinary&&(ha=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!==typeof WebAssembly&&n("no native wasm support detected");var ia,ja=!1;
function ka(a,b,c){var d={string:function(p){var r=0;if(null!==p&&void 0!==p&&0!==p){var q=(p.length<<2)+1;r=la(q);u(p,v,r,q)}return r},array:function(p){var r=la(p.length);x.set(p,r);return r}};a=h["_"+a];var e=[],f=0;if(c)for(var g=0;g<c.length;g++){var k=d[b[g]];k?(0===f&&(f=ma()),e[g]=k(c[g])):e[g]=c[g]}b=a.apply(null,e);b=function(p){0!==f&&na(f);return p}(b)}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function y(a,b){return a?qa(v,a,b):""}
function u(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function sa(a){var b=ra(a)+1,c=la(b);u(a,x,c,b);return c}var ta,x,v,ua,va,z,wa,A,B,xa,ya=[],za=[],Aa=[],Ba=[],Ca=[];function Da(){var a=h.preRun.shift();ya.unshift(a)}var C=0,Ea=null,Fa=null;h.preloadedImages={};h.preloadedAudios={};
function n(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";m(a);ja=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ga(){return D.startsWith("data:application/octet-stream;base64,")}var D;D="SkyBoy.wasm";if(!Ga()){var Ha=D;D=h.locateFile?h.locateFile(Ha,l):l+Ha}function Ia(){var a=D;try{if(a==D&&ha)return new Uint8Array(ha);throw"both async and sync fetching of the wasm failed";}catch(b){n(b)}}
function Ja(){return ha||"function"!==typeof fetch?Promise.resolve().then(function(){return Ia()}):fetch(D,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+D+"'";return a.arrayBuffer()}).catch(function(){return Ia()})}
var E,Ka,Oa={153128:function(){document.getElementById("fileInput").style.visibility="hidden"},153216:function(a,b,c,d){var e=document.getElementById("fileInput");e.style.left=a+"px";e.style.top=b+"px";e.style.width=c+"px";e.style.height=d+"px";e.style.visibility="visible";if(""!=e.value){console.log(e.value);var f=new FileReader;a=e.files[0];f.addEventListener("loadend",function(){const k=new Uint8Array(f.result);var p="/offline/"+g;La(p,k);Ma(function(){});document.getElementById("fileStaging").value=
p});f.readAsArrayBuffer(a);var g=a.name;e.value=""}a=document.getElementById("fileStaging");e="";""!=a.value&&(e=a.value,a.value="");a=ra(e)+1;b=F(a);u(e,v,b,a);return b},154240:function(){Ma(function(){})},154270:function(){Ma(function(){})},154300:function(){G("/offline");Na(H,"/offline");Ma(!0,function(){})}};function Pa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.Kd;"number"===typeof c?void 0===b.wc?I(c)():I(c)(b.wc):c(void 0===b.wc?null:b.wc)}}}var Qa=[];
function I(a){var b=Qa[a];b||(a>=Qa.length&&(Qa.length=a+1),Qa[a]=b=xa.get(a));return b}function Ra(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Sa(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ra(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ta(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ua(a){if("/"===a)return"/";a=Sa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Va(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){n("randomDevice")}}
function Wa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ra(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Xa=[];function Ya(a,b){Xa[a]={input:[],Ob:[],ec:b};Za(a,$a)}
var $a={open:function(a){var b=Xa[a.node.qc];if(!b)throw new J(43);a.Mb=b;a.seekable=!1},close:function(a){a.Mb.ec.flush(a.Mb)},flush:function(a){a.Mb.ec.flush(a.Mb)},read:function(a,b,c,d){if(!a.Mb||!a.Mb.ec.Oc)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.Mb.ec.Oc(a.Mb)}catch(k){throw new J(29);}if(void 0===g&&0===e)throw new J(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Mb||!a.Mb.ec.zc)throw new J(60);try{for(var e=
0;e<d;e++)a.Mb.ec.zc(a.Mb,b[c+e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},ab={Oc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;var c=Array(ra(b)+1);b=u(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},zc:function(a,b){null===b||10===b?(fa(qa(a.Ob,0)),a.Ob=[]):0!=b&&a.Ob.push(b)},
flush:function(a){a.Ob&&0<a.Ob.length&&(fa(qa(a.Ob,0)),a.Ob=[])}},bb={zc:function(a,b){null===b||10===b?(m(qa(a.Ob,0)),a.Ob=[]):0!=b&&a.Ob.push(b)},flush:function(a){a.Ob&&0<a.Ob.length&&(m(qa(a.Ob,0)),a.Ob=[])}},K={Tb:null,Qb:function(){return K.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.Tb||(K.Tb={dir:{node:{Sb:K.Ib.Sb,Pb:K.Ib.Pb,fc:K.Ib.fc,pc:K.Ib.pc,Uc:K.Ib.Uc,uc:K.Ib.uc,sc:K.Ib.sc,rc:K.Ib.rc,tc:K.Ib.tc},stream:{ac:K.Kb.ac}},
file:{node:{Sb:K.Ib.Sb,Pb:K.Ib.Pb},stream:{ac:K.Kb.ac,read:K.Kb.read,write:K.Kb.write,Gc:K.Kb.Gc,Qc:K.Kb.Qc,Sc:K.Kb.Sc}},link:{node:{Sb:K.Ib.Sb,Pb:K.Ib.Pb,ic:K.Ib.ic},stream:{}},Ic:{node:{Sb:K.Ib.Sb,Pb:K.Ib.Pb},stream:cb}});c=db(a,b,c,d);L(c.mode)?(c.Ib=K.Tb.dir.node,c.Kb=K.Tb.dir.stream,c.Jb={}):32768===(c.mode&61440)?(c.Ib=K.Tb.file.node,c.Kb=K.Tb.file.stream,c.Lb=0,c.Jb=null):40960===(c.mode&61440)?(c.Ib=K.Tb.link.node,c.Kb=K.Tb.link.stream):8192===(c.mode&61440)&&(c.Ib=K.Tb.Ic.node,c.Kb=K.Tb.Ic.stream);
c.timestamp=Date.now();a&&(a.Jb[b]=c,a.timestamp=c.timestamp);return c},ld:function(a){return a.Jb?a.Jb.subarray?a.Jb.subarray(0,a.Lb):new Uint8Array(a.Jb):new Uint8Array(0)},Lc:function(a,b){var c=a.Jb?a.Jb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Jb,a.Jb=new Uint8Array(b),0<a.Lb&&a.Jb.set(c.subarray(0,a.Lb),0))},wd:function(a,b){if(a.Lb!=b)if(0==b)a.Jb=null,a.Lb=0;else{var c=a.Jb;a.Jb=new Uint8Array(b);c&&a.Jb.set(c.subarray(0,Math.min(b,a.Lb)));a.Lb=
b}},Ib:{Sb:function(a){var b={};b.Id=8192===(a.mode&61440)?a.id:1;b.Nd=a.id;b.mode=a.mode;b.Qd=1;b.uid=0;b.Ld=0;b.qc=a.qc;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Lb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Ed=new Date(a.timestamp);b.yc=new Date(a.timestamp);b.Gd=new Date(a.timestamp);b.ed=4096;b.Fd=Math.ceil(b.size/b.ed);return b},Pb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.wd(a,b.size)},fc:function(){throw eb[44];
},pc:function(a,b,c,d){return K.createNode(a,b,c,d)},Uc:function(a,b,c){if(L(a.mode)){try{var d=M(b,c)}catch(f){}if(d)for(var e in d.Jb)throw new J(55);}delete a.parent.Jb[a.name];a.parent.timestamp=Date.now();a.name=c;b.Jb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},uc:function(a,b){delete a.Jb[b];a.timestamp=Date.now()},sc:function(a,b){var c=M(a,b),d;for(d in c.Jb)throw new J(55);delete a.Jb[b];a.timestamp=Date.now()},rc:function(a){var b=[".",".."],c;for(c in a.Jb)a.Jb.hasOwnProperty(c)&&
b.push(c);return b},tc:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},ic:function(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},Kb:{read:function(a,b,c,d,e){var f=a.node.Jb;if(e>=a.node.Lb)return 0;a=Math.min(a.node.Lb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Jb||a.Jb.subarray)){if(f)return a.Jb=b.subarray(c,c+d),a.Lb=d;
if(0===a.Lb&&0===e)return a.Jb=b.slice(c,c+d),a.Lb=d;if(e+d<=a.Lb)return a.Jb.set(b.subarray(c,c+d),e),d}K.Lc(a,e+d);if(a.Jb.subarray&&b.subarray)a.Jb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Jb[e+f]=b[c+f];a.Lb=Math.max(a.Lb,e+d);return d},ac:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Lb);if(0>b)throw new J(28);return b},Gc:function(a,b,c){K.Lc(a.node,b+c);a.node.Lb=Math.max(a.node.Lb,b+c)},Qc:function(a,b,c,d,e,f){if(0!==b)throw new J(28);if(32768!==
(a.node.mode&61440))throw new J(43);a=a.node.Jb;if(f&2||a.buffer!==ta){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;n();c=void 0;if(!c)throw new J(48);x.set(a,c)}else d=!1,c=a.byteOffset;return{Td:c,Cd:d}},Sc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;K.Kb.write(a,b,0,d,c,!1);return 0}}},H={Jc:{},indexedDB:function(){if("undefined"!==typeof indexedDB)return indexedDB;var a=null;"object"===typeof window&&(a=window.indexedDB||
window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB);a||n("IDBFS used, but indexedDB not supported");return a},dd:21,$b:"FILE_DATA",Qb:function(a){return K.Qb.apply(null,arguments)},ad:function(a,b,c){H.md(a,function(d,e){if(d)return c(d);H.nd(a,function(f,g){if(f)return c(f);H.td(b?g:e,b?e:g,c)})})},kd:function(a,b){var c=H.Jc[a];if(c)return b(null,c);try{var d=H.indexedDB().open(a,H.dd)}catch(e){return b(e)}if(!d)return b("Unable to connect to IndexedDB");d.onupgradeneeded=function(e){var f=
e.target.result;e=e.target.transaction;f=f.objectStoreNames.contains(H.$b)?e.objectStore(H.$b):f.createObjectStore(H.$b);f.indexNames.contains("timestamp")||f.createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=function(){c=d.result;H.Jc[a]=c;b(null,c)};d.onerror=function(e){b(this.error);e.preventDefault()}},md:function(a,b){function c(k){return"."!==k&&".."!==k}function d(k){return function(p){return Sa(k+"/"+p)}}var e={};for(a=fb(a.hc).filter(c).map(d(a.hc));a.length;){var f=a.pop();
try{var g=gb(f)}catch(k){return b(k)}L(g.mode)&&a.push.apply(a,fb(f).filter(c).map(d(f)));e[f]={timestamp:g.yc}}return b(null,{type:"local",entries:e})},nd:function(a,b){var c={};H.kd(a.hc,function(d,e){if(d)return b(d);try{var f=e.transaction([H.$b],"readonly");f.onerror=function(g){b(this.error);g.preventDefault()};f.objectStore(H.$b).index("timestamp").openKeyCursor().onsuccess=function(g){g=g.target.result;if(!g)return b(null,{type:"remote",db:e,entries:c});c[g.primaryKey]={timestamp:g.key};g.continue()}}catch(g){return b(g)}})},
qd:function(a,b){try{var c=N(a).node;var d=gb(a)}catch(e){return b(e)}return L(d.mode)?b(null,{timestamp:d.yc,mode:d.mode}):32768===(d.mode&61440)?(c.Jb=K.ld(c),b(null,{timestamp:d.yc,mode:d.mode,contents:c.Jb})):b(Error("node type not supported"))},yd:function(a,b,c){try{if(L(b.mode))for(var d=b.mode,e=a.split("/"),f="",g=0;g<e.length;++g){if(e[g]){f+="/"+e[g];try{G(f,d)}catch(w){if(20!=w.Ub)throw w;}}}else if(32768===(b.mode&61440))La(a,b.contents,{Hc:!0});else return c(Error("node type not supported"));
var k=b.mode;var p="string"===typeof a?N(a,{bc:!0}).node:a;if(!p.Ib.Pb)throw new J(63);p.Ib.Pb(p,{mode:k&4095|p.mode&-4096,timestamp:Date.now()});var r=b.timestamp,q=b.timestamp,t=N(a,{bc:!0}).node;t.Ib.Pb(t,{timestamp:Math.max(r,q)})}catch(w){return c(w)}c(null)},ud:function(a,b){try{N(a);var c=gb(a);if(L(c.mode)){var d=N(a,{parent:!0}).node,e=Ua(a),f=M(d,e),g=hb(d,e,!0);if(g)throw new J(g);if(!d.Ib.sc)throw new J(63);if(f.cc)throw new J(10);d.Ib.sc(d,e);ib(f)}else if(32768===(c.mode&61440)){var k=
N(a,{parent:!0}).node;if(!k)throw new J(44);var p=Ua(a),r=M(k,p),q=hb(k,p,!1);if(q)throw new J(q);if(!k.Ib.uc)throw new J(63);if(r.cc)throw new J(10);k.Ib.uc(k,p);ib(r)}}catch(t){return b(t)}b(null)},rd:function(a,b,c){a=a.get(b);a.onsuccess=function(d){c(null,d.target.result)};a.onerror=function(d){c(this.error);d.preventDefault()}},zd:function(a,b,c,d){try{var e=a.put(c,b)}catch(f){d(f);return}e.onsuccess=function(){d(null)};e.onerror=function(f){d(this.error);f.preventDefault()}},vd:function(a,
b,c){a=a.delete(b);a.onsuccess=function(){c(null)};a.onerror=function(d){c(this.error);d.preventDefault()}},td:function(a,b,c){function d(q){if(q&&!k)return k=!0,c(q)}var e=0,f=[];Object.keys(a.entries).forEach(function(q){var t=a.entries[q],w=b.entries[q];w&&t.timestamp.getTime()==w.timestamp.getTime()||(f.push(q),e++)});var g=[];Object.keys(b.entries).forEach(function(q){a.entries[q]||(g.push(q),e++)});if(!e)return c(null);var k=!1,p=("remote"===a.type?a.db:b.db).transaction([H.$b],"readwrite"),
r=p.objectStore(H.$b);p.onerror=function(q){d(this.error);q.preventDefault()};p.oncomplete=function(){k||c(null)};f.sort().forEach(function(q){"local"===b.type?H.rd(r,q,function(t,w){if(t)return d(t);H.yd(q,w,d)}):H.qd(q,function(t,w){if(t)return d(t);H.zd(r,q,w,d)})});g.sort().reverse().forEach(function(q){"local"===b.type?H.ud(q,d):H.vd(r,q,d)})}},jb=null,kb={},lb=[],mb=1,O=null,nb=!0,J=null,eb={},qb=0;
function N(a,b){a=Wa("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Mc:!0,Ac:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ac)throw new J(32);a=Ra(a.split("/").filter(function(g){return!!g}),!1);var e=jb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=M(e,a[d]);c=Sa(c+"/"+a[d]);e.cc&&(!f||f&&b.Mc)&&(e=e.cc.root);if(!f||b.bc)for(f=0;40960===(e.mode&61440);)if(e=rb(c),c=Wa(Ta(c),e),e=N(c,{Ac:b.Ac}).node,40<f++)throw new J(32);}return{path:c,node:e}}
function sb(a){for(var b;;){if(a===a.parent)return a=a.Qb.hc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function tb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length}function ib(a){var b=tb(a.parent.id,a.name);if(O[b]===a)O[b]=a.dc;else for(b=O[b];b;){if(b.dc===a){b.dc=a.dc;break}b=b.dc}}
function M(a,b){var c;if(c=(c=ub(a,"x"))?c:a.Ib.fc?0:2)throw new J(c,a);for(c=O[tb(a.id,b)];c;c=c.dc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ib.fc(a,b)}function db(a,b,c,d){a=new vb(a,b,c,d);b=tb(a.parent.id,a.name);a.dc=O[b];return O[b]=a}function L(a){return 16384===(a&61440)}var wb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function xb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function ub(a,b){if(nb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function yb(a,b){try{return M(a,b),20}catch(c){}return ub(a,"wx")}function hb(a,b,c){try{var d=M(a,b)}catch(e){return e.Ub}if(a=ub(a,"wx"))return a;if(c){if(!L(d.mode))return 54;if(d===d.parent||"/"===sb(d))return 10}else if(L(d.mode))return 31;return 0}function zb(a){var b=4096;for(a=a||0;a<=b;a++)if(!lb[a])return a;throw new J(33);}
function Ab(a,b){Bb||(Bb=function(){},Bb.prototype={});var c=new Bb,d;for(d in a)c[d]=a[d];a=c;b=zb(b);a.Yb=b;return lb[b]=a}var cb={open:function(a){a.Kb=kb[a.node.qc].Kb;a.Kb.open&&a.Kb.open(a)},ac:function(){throw new J(70);}};function Za(a,b){kb[a]={Kb:b}}function Cb(){for(var a=[],b=[jb.Qb];b.length;){var c=b.pop();a.push(c);b.push.apply(b,c.Rc)}return a}
function Ma(a,b){function c(g){qb--;return b(g)}function d(g){if(g){if(!d.gd)return d.gd=!0,c(g)}else++f>=e.length&&c(null)}"function"===typeof a&&(b=a,a=!1);qb++;1<qb&&m("warning: "+qb+" FS.syncfs operations in flight at once, probably just doing extra work");var e=Cb(),f=0;e.forEach(function(g){if(!g.type.ad)return d(null);g.type.ad(g,a,d)})}
function Na(a,b){var c="/"===b,d=!b;if(c&&jb)throw new J(10);if(!c&&!d){var e=N(b,{Mc:!1});b=e.path;e=e.node;if(e.cc)throw new J(10);if(!L(e.mode))throw new J(54);}b={type:a,Rd:{},hc:b,Rc:[]};a=a.Qb(b);a.Qb=b;b.root=a;c?jb=a:e&&(e.cc=b,e.Qb&&e.Qb.Rc.push(b))}function Db(a,b,c){var d=N(a,{parent:!0}).node;a=Ua(a);if(!a||"."===a||".."===a)throw new J(28);var e=yb(d,a);if(e)throw new J(e);if(!d.Ib.pc)throw new J(63);return d.Ib.pc(d,a,b,c)}
function G(a,b){return Db(a,(void 0!==b?b:511)&1023|16384,0)}function Eb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Db(a,b|8192,c)}function Fb(a,b){if(!Wa(a))throw new J(44);var c=N(b,{parent:!0}).node;if(!c)throw new J(44);b=Ua(b);var d=yb(c,b);if(d)throw new J(d);if(!c.Ib.tc)throw new J(63);c.Ib.tc(c,b,a)}function fb(a){a=N(a,{bc:!0}).node;if(!a.Ib.rc)throw new J(54);return a.Ib.rc(a)}
function rb(a){a=N(a).node;if(!a)throw new J(44);if(!a.Ib.ic)throw new J(28);return Wa(sb(a.parent),a.Ib.ic(a))}function gb(a){a=N(a,{bc:!0}).node;if(!a)throw new J(44);if(!a.Ib.Sb)throw new J(63);return a.Ib.Sb(a)}
function P(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=wb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Sa(a);try{f=N(a,{bc:!(b&131072)}).node}catch(g){}}e=!1;if(b&64)if(f){if(b&128)throw new J(20);}else f=Db(a,c,0),e=!0;if(!f)throw new J(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!L(f.mode))throw new J(54);if(!e&&(c=f?40960===(f.mode&61440)?32:L(f.mode)&&
("r"!==xb(b)||b&512)?31:ub(f,xb(b)):44))throw new J(c);if(b&512){c=f;c="string"===typeof c?N(c,{bc:!0}).node:c;if(!c.Ib.Pb)throw new J(63);if(L(c.mode))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(e=ub(c,"w"))throw new J(e);c.Ib.Pb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Ab({node:f,path:sb(f),id:f.id,flags:b,mode:f.mode,seekable:!0,position:0,Kb:f.Kb,Ib:f.Ib,Ad:[],error:!1},d);d.Kb.open&&d.Kb.open(d);!h.logReadFiles||b&1||(Gb||(Gb={}),a in Gb||(Gb[a]=1));return d}
function Hb(a){if(null===a.Yb)throw new J(8);a.xc&&(a.xc=null);try{a.Kb.close&&a.Kb.close(a)}catch(b){throw b;}finally{lb[a.Yb]=null}a.Yb=null}function Ib(a,b,c){if(null===a.Yb)throw new J(8);if(!a.seekable||!a.Kb.ac)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.Kb.ac(a,b,c);a.Ad=[]}
function Jb(a,b,c,d,e){var f=void 0;if(0>d||0>f)throw new J(28);if(null===a.Yb)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(L(a.node.mode))throw new J(31);if(!a.Kb.write)throw new J(28);a.seekable&&a.flags&1024&&Ib(a,0,2);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new J(70);b=a.Kb.write(a,b,c,d,f,e);g||(a.position+=b);return b}
function La(a,b,c){c=c||{};c.flags=c.flags||577;a=P(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(ra(b)+1);b=u(b,d,0,d.length);Jb(a,d,0,b,c.Hc)}else if(ArrayBuffer.isView(b))Jb(a,b,0,b.byteLength,c.Hc);else throw Error("Unsupported data type");Hb(a)}
function Kb(){J||(J=function(a,b){this.node=b;this.xd=function(c){this.Ub=c};this.xd(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){eb[a]=new J(a);eb[a].stack="<generic error, no stack>"}))}var Lb;function Mb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Nb(a,b,c){a=Sa("/dev/"+a);var d=Mb(!!b,!!c);Ob||(Ob=64);var e=Ob++<<8|0;Za(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,g,k,p){for(var r=0,q=0;q<p;q++){try{var t=b()}catch(w){throw new J(29);}if(void 0===t&&0===r)throw new J(6);if(null===t||void 0===t)break;r++;g[k+q]=t}r&&(f.node.timestamp=Date.now());return r},write:function(f,g,k,p){for(var r=0;r<p;r++)try{c(g[k+r])}catch(q){throw new J(29);}p&&(f.node.timestamp=Date.now());return r}});
Eb(a,d,e)}var Ob,Q={},Bb,Gb,Pb=void 0;function R(){Pb+=4;return z[Pb-4>>2]}function S(a){a=lb[a];if(!a)throw new J(8);return a}var Qb=[],Rb=0;function Sb(){for(var a=T.length-1;0<=a;--a)Tb(a);T=[];Ub=[]}var Ub=[];function Vb(){if(Rb&&Wb.lc)for(var a=0;a<Ub.length;++a){var b=Ub[a];Ub.splice(a,1);--a;b.Wd.apply(null,b.Dd)}}var T=[];function Tb(a){var b=T[a];b.target.removeEventListener(b.Rb,b.hd,b.Vb);T.splice(a,1)}
function U(a){function b(d){++Rb;Wb=a;Vb();a.Zb(d);Vb();--Rb}if(a.Xb)a.hd=b,a.target.addEventListener(a.Rb,b,a.Vb),T.push(a),Xb||(Ba.push(Sb),Xb=!0);else for(var c=0;c<T.length;++c)T[c].target==a.target&&T[c].Rb==a.Rb&&Tb(c--)}var Xb,Wb,Yb,Zb,$b,ac,bc,cc,dc=[0,document,window];function V(a){a=2<a?y(a):a;return dc[a]||document.querySelector(a)}function ec(a){return 0>dc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function fc(a,b,c,d,e,f){Yb||(Yb=F(176));a={target:V(a),lc:!0,Rb:f,Xb:d,Zb:function(g){var k=Yb;B[k>>3]=g.timeStamp;var p=k>>2;z[p+2]=g.location;z[p+3]=g.ctrlKey;z[p+4]=g.shiftKey;z[p+5]=g.altKey;z[p+6]=g.metaKey;z[p+7]=g.repeat;z[p+8]=g.charCode;z[p+9]=g.keyCode;z[p+10]=g.which;u(g.key||"",v,k+44,32);u(g.code||"",v,k+76,32);u(g.char||"",v,k+108,32);u(g.locale||"",v,k+140,32);I(d)(e,k,b)&&g.preventDefault()},Vb:c};U(a)}
function gc(a,b,c){B[a>>3]=b.timeStamp;a>>=2;z[a+2]=b.screenX;z[a+3]=b.screenY;z[a+4]=b.clientX;z[a+5]=b.clientY;z[a+6]=b.ctrlKey;z[a+7]=b.shiftKey;z[a+8]=b.altKey;z[a+9]=b.metaKey;ua[2*a+20]=b.button;ua[2*a+21]=b.buttons;z[a+11]=b.movementX;z[a+12]=b.movementY;c=ec(c);z[a+13]=b.clientX-c.left;z[a+14]=b.clientY-c.top}
function hc(a,b,c,d,e,f){Zb||(Zb=F(72));a=V(a);U({target:a,lc:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Rb:f,Xb:d,Zb:function(g){g=g||event;gc(Zb,g,a);I(d)(e,Zb,b)&&g.preventDefault()},Vb:c})}
function ic(a,b,c,d,e){$b||($b=F(260));U({target:a,Rb:e,Xb:d,Zb:function(f){f=f||event;var g=$b,k=document.pointerLockElement||document.Dc||document.Fc||document.Ec;z[g>>2]=!!k;var p=k&&k.id?k.id:"";u(k?k==window?"#window":k==screen?"#screen":k&&k.nodeName?k.nodeName:"":"",v,g+4,128);u(p,v,g+132,128);I(d)(20,g,b)&&f.preventDefault()},Vb:c})}function jc(a,b,c,d,e){U({target:a,Rb:e,Xb:d,Zb:function(f){f=f||event;I(d)(38,0,b)&&f.preventDefault()},Vb:c})}
function kc(a,b,c,d){ac||(ac=F(36));a=V(a);U({target:a,Rb:"resize",Xb:d,Zb:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=ac;z[g>>2]=e.detail;z[g+4>>2]=f.clientWidth;z[g+8>>2]=f.clientHeight;z[g+12>>2]=innerWidth;z[g+16>>2]=innerHeight;z[g+20>>2]=outerWidth;z[g+24>>2]=outerHeight;z[g+28>>2]=pageXOffset;z[g+32>>2]=pageYOffset;I(d)(10,g,b)&&e.preventDefault()}}},Vb:c})}
function lc(a,b,c,d,e,f){bc||(bc=F(1696));a=V(a);U({target:a,lc:"touchstart"==f||"touchend"==f,Rb:f,Xb:d,Zb:function(g){for(var k,p={},r=g.touches,q=0;q<r.length;++q)k=r[q],k.Pc=k.Tc=0,p[k.identifier]=k;for(q=0;q<g.changedTouches.length;++q)k=g.changedTouches[q],k.Pc=1,p[k.identifier]=k;for(q=0;q<g.targetTouches.length;++q)p[g.targetTouches[q].identifier].Tc=1;r=bc;B[r>>3]=g.timeStamp;var t=r>>2;z[t+3]=g.ctrlKey;z[t+4]=g.shiftKey;z[t+5]=g.altKey;z[t+6]=g.metaKey;t+=7;var w=ec(a),oa=0;for(q in p)if(k=
p[q],z[t]=k.identifier,z[t+1]=k.screenX,z[t+2]=k.screenY,z[t+3]=k.clientX,z[t+4]=k.clientY,z[t+5]=k.pageX,z[t+6]=k.pageY,z[t+7]=k.Pc,z[t+8]=k.Tc,z[t+9]=k.clientX-w.left,z[t+10]=k.clientY-w.top,t+=13,31<++oa)break;z[r+8>>2]=oa;I(d)(e,r,b)&&g.preventDefault()},Vb:c})}function mc(a,b,c,d,e,f){a={target:V(a),Rb:f,Xb:d,Zb:function(g){g=g||event;I(d)(e,0,b)&&g.preventDefault()},Vb:c};U(a)}
function nc(a,b,c,d){cc||(cc=F(104));U({target:a,lc:!0,Rb:"wheel",Xb:d,Zb:function(e){e=e||event;var f=cc;gc(f,e,a);B[f+72>>3]=e.deltaX;B[f+80>>3]=e.deltaY;B[f+88>>3]=e.deltaZ;z[f+96>>2]=e.deltaMode;I(d)(9,f,b)&&e.preventDefault()},Vb:c})}
function oc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function pc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function qc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function sc(a){a.Pd=a.getExtension("WEBGL_multi_draw")}
var tc=1,uc=[],W=[],vc=[],wc=[],xc=[],X=[],yc=[],zc={};function Y(a){Ac||(Ac=a)}function Bc(a){for(var b=tc++,c=a.length;c<b;c++)a[c]=null;return b}function Cc(a,b){a.Nc||(a.Nc=a.getContext,a.getContext=function(d,e){e=a.Nc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Dc(c,b):0}function Dc(a,b){var c=Bc(yc),d={Md:c,attributes:b,version:b.sd,vc:a};a.canvas&&(a.canvas.Bd=d);yc[c]=d;("undefined"===typeof b.Kc||b.Kc)&&Ec(d);return c}
function Ec(a){a||(a=Fc);if(!a.od){a.od=!0;var b=a.vc;oc(b);pc(b);qc(b);b.Jd=b.getExtension("EXT_disjoint_timer_query");sc(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Ac,Fc,Gc=["default","low-power","high-performance"];function Hc(a,b,c,d){for(var e=0;e<a;e++){var f=Z[c](),g=f&&Bc(d);f?(f.name=g,d[g]=f):Y(1282);z[b+4*e>>2]=g}}
function Ic(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)z[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Y(1280);m("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:Y(1280);m("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}z[b>>2]=c}else Y(1281)}function Jc(a){var b=ra(a)+1,c=F(b);u(a,v,c,b);return c}
function Kc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Lc(a){var b=Z.fd;if(b){var c=b.kc[a];"number"===typeof c&&(b.kc[a]=c=Z.getUniformLocation(b,b.bd[a]+(0<c?"["+c+"]":"")));return c}Y(1282)}var Mc=[];function vb(a,b,c,d){a||(a=this);this.parent=a;this.Qb=a.Qb;this.cc=null;this.id=mb++;this.name=b;this.mode=c;this.Ib={};this.Kb={};this.qc=d}
Object.defineProperties(vb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Kb();O=Array(4096);Na(K,"/");G("/tmp");G("/home");G("/home/web_user");
(function(){G("/dev");Za(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Eb("/dev/null",259);Ya(1280,ab);Ya(1536,bb);Eb("/dev/tty",1280);Eb("/dev/tty1",1536);var a=Va();Nb("random",a);Nb("urandom",a);G("/dev/shm");G("/dev/shm/tmp")})();
(function(){G("/proc");var a=G("/proc/self");G("/proc/self/fd");Na({Qb:function(){var b=db(a,"fd",16895,73);b.Ib={fc:function(c,d){var e=lb[+d];if(!e)throw new J(8);c={parent:null,Qb:{hc:"fake"},Ib:{ic:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();for(var Z,Nc=new Float32Array(288),Oc=0;288>Oc;++Oc)Mc[Oc]=Nc.subarray(0,Oc+1);
var Wc={oa:function(a,b,c){Pb=c;try{var d=S(a);switch(b){case 0:var e=R();return 0>e?-28:P(d.path,d.flags,0,e).Yb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=R(),d.flags|=e,0;case 5:return e=R(),ua[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return z[Pc()>>2]=28,-1;default:return-28}}catch(f){if("undefined"===typeof Q||!(f instanceof J))throw f;return-f.Ub}},eb:function(a,b,c){Pb=c;try{var d=S(a);switch(b){case 21509:case 21505:return d.Mb?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Mb?
0:-59;case 21519:if(!d.Mb)return-59;var e=R();return z[e>>2]=0;case 21520:return d.Mb?-28:-59;case 21531:a=e=R();if(!d.Kb.pd)throw new J(59);return d.Kb.pd(d,b,a);case 21523:return d.Mb?0:-59;case 21524:return d.Mb?0:-59;default:n("bad ioctl syscall "+b)}}catch(f){if("undefined"===typeof Q||!(f instanceof J))throw f;return-f.Ub}},fb:function(a,b,c){Pb=c;try{var d=y(a),e=c?R():0;return P(d,b,e).Yb}catch(f){if("undefined"===typeof Q||!(f instanceof J))throw f;return-f.Ub}},k:function(a,b,c){Qb.length=
0;var d;for(c>>=2;d=v[b++];)(d=105>d)&&c&1&&c++,Qb.push(d?B[c++>>1]:z[c]),++c;return Oa[a].apply(null,Qb)},X:function(){return devicePixelRatio},ea:function(a,b,c){a=V(a);if(!a)return-4;a=ec(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},bb:function(a,b,c){v.copyWithin(a,b,b+c)},Xa:function(a,b){function c(d){I(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},y:function(){n("OOM")},W:function(a,b,c){a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0},ia:function(a,b,c,d){fc(a,b,
c,d,2,"keydown");return 0},ga:function(a,b,c,d){fc(a,b,c,d,1,"keypress");return 0},ha:function(a,b,c,d){fc(a,b,c,d,3,"keyup");return 0},sa:function(a,b,c,d){hc(a,b,c,d,5,"mousedown");return 0},la:function(a,b,c,d){hc(a,b,c,d,33,"mouseenter");return 0},ka:function(a,b,c,d){hc(a,b,c,d,34,"mouseleave");return 0},na:function(a,b,c,d){hc(a,b,c,d,8,"mousemove");return 0},qa:function(a,b,c,d){hc(a,b,c,d,6,"mouseup");return 0},aa:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||
document.body.Dc||document.body.Fc||document.body.Ec))return-1;a=V(a);if(!a)return-4;ic(a,b,c,d,"pointerlockchange");ic(a,b,c,d,"mozpointerlockchange");ic(a,b,c,d,"webkitpointerlockchange");ic(a,b,c,d,"mspointerlockchange");return 0},$:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Dc||document.body.Fc||document.body.Ec))return-1;a=V(a);if(!a)return-4;jc(a,b,c,d,"pointerlockerror");jc(a,b,c,d,"mozpointerlockerror");jc(a,b,c,d,"webkitpointerlockerror");jc(a,b,c,d,
"mspointerlockerror");return 0},Ya:function(a,b,c,d){kc(a,b,c,d);return 0},ba:function(a,b,c,d){lc(a,b,c,d,25,"touchcancel");return 0},ca:function(a,b,c,d){lc(a,b,c,d,23,"touchend");return 0},da:function(a,b,c,d){lc(a,b,c,d,24,"touchmove");return 0},fa:function(a,b,c,d){lc(a,b,c,d,22,"touchstart");return 0},_:function(a,b,c,d){mc(a,b,c,d,31,"webglcontextlost");return 0},Z:function(a,b,c,d){mc(a,b,c,d,32,"webglcontextrestored");return 0},ja:function(a,b,c,d){a=V(a);return"undefined"!==typeof a.onwheel?
(nc(a,b,c,d),0):-1},Q:function(a,b){b>>=2;b={alpha:!!z[b],depth:!!z[b+1],stencil:!!z[b+2],antialias:!!z[b+3],premultipliedAlpha:!!z[b+4],preserveDrawingBuffer:!!z[b+5],powerPreference:Gc[z[b+6]],failIfMajorPerformanceCaveat:!!z[b+7],sd:z[b+8],Od:z[b+9],Kc:z[b+10],jd:z[b+11],Sd:z[b+12],Ud:z[b+13]};a=V(a);return!a||b.jd?0:Cc(a,b)},za:function(a,b){a=yc[a];b=y(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&oc(Z);"OES_vertex_array_object"==b&&pc(Z);"WEBGL_draw_buffers"==b&&qc(Z);
"WEBGL_multi_draw"==b&&sc(Z);return!!a.vc.getExtension(b)},Ia:function(a){a>>=2;for(var b=0;14>b;++b)z[a+b]=0;z[a]=z[a+1]=z[a+3]=z[a+4]=z[a+8]=z[a+10]=1},Da:function(a){Fc=yc[a];h.Hd=Z=Fc&&Fc.vc;return!a||Z?0:-5},ma:function(a){try{var b=S(a);Hb(b);return 0}catch(c){if("undefined"===typeof Q||!(c instanceof J))throw c;return c.Ub}},db:function(a,b,c,d){try{a:{for(var e=S(a),f=a=0;f<c;f++){var g=z[b+(8*f+4)>>2],k=e,p=z[b+8*f>>2],r=g,q=void 0,t=x;if(0>r||0>q)throw new J(28);if(null===k.Yb)throw new J(8);
if(1===(k.flags&2097155))throw new J(8);if(L(k.node.mode))throw new J(31);if(!k.Kb.read)throw new J(28);var w="undefined"!==typeof q;if(!w)q=k.position;else if(!k.seekable)throw new J(70);var oa=k.Kb.read(k,t,p,r,q);w||(k.position+=oa);var ob=oa;if(0>ob){var rc=-1;break a}a+=ob;if(ob<g)break}rc=a}z[d>>2]=rc;return 0}catch(pb){if("undefined"===typeof Q||!(pb instanceof J))throw pb;return pb.Ub}},ab:function(a,b,c,d,e){try{var f=S(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=
a)return-61;Ib(f,a,d);Ka=[f.position>>>0,(E=f.position,1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];z[e>>2]=Ka[0];z[e+4>>2]=Ka[1];f.xc&&0===a&&0===d&&(f.xc=null);return 0}catch(g){if("undefined"===typeof Q||!(g instanceof J))throw g;return g.Ub}},cb:function(a,b,c,d){try{a:{for(var e=S(a),f=a=0;f<c;f++){var g=Jb(e,x,z[b+8*f>>2],z[b+(8*f+4)>>2]);if(0>g){var k=-1;break a}a+=g}k=a}z[d>>2]=k;return 0}catch(p){if("undefined"===
typeof Q||!(p instanceof J))throw p;return p.Ub}},b:function(a){Z.activeTexture(a)},V:function(a,b){Z.attachShader(W[a],X[b])},c:function(a,b){Z.bindBuffer(a,uc[b])},S:function(a,b){Z.bindFramebuffer(a,vc[b])},Qa:function(a,b){Z.bindRenderbuffer(a,wc[b])},a:function(a,b){Z.bindTexture(a,xc[b])},K:function(a,b,c,d){Z.blendColor(a,b,c,d)},L:function(a,b){Z.blendEquationSeparate(a,b)},M:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},Sa:function(a,b,c,d){Z.bufferData(a,c?v.subarray(c,c+b):b,d)},o:function(a,
b,c,d){Z.bufferSubData(a,b,v.subarray(d,d+c))},Ea:function(a){Z.clear(a)},Ga:function(a,b,c,d){Z.clearColor(a,b,c,d)},R:function(a){Z.clearDepth(a)},Fa:function(a){Z.clearStencil(a)},i:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},hb:function(a){Z.compileShader(X[a])},Na:function(a,b,c,d,e,f,g,k){Z.compressedTexImage2D(a,b,c,d,e,f,k?v.subarray(k,k+g):null)},La:function(){var a=Bc(W),b=Z.createProgram();b.name=a;b.oc=b.mc=b.nc=0;b.Cc=1;W[a]=b;return a},jb:function(a){var b=Bc(X);X[b]=Z.createShader(a);
return b},J:function(a){Z.cullFace(a)},nb:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=uc[d];e&&(Z.deleteBuffer(e),e.name=0,uc[d]=null)}},h:function(a,b){for(var c=0;c<a;++c){var d=z[b+4*c>>2],e=vc[d];e&&(Z.deleteFramebuffer(e),e.name=0,vc[d]=null)}},x:function(a){if(a){var b=W[a];b?(Z.deleteProgram(b),b.name=0,W[a]=null):Y(1281)}},ra:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=wc[d];e&&(Z.deleteRenderbuffer(e),e.name=0,wc[d]=null)}},w:function(a){if(a){var b=X[a];b?(Z.deleteShader(b),
X[a]=null):Y(1281)}},mb:function(a,b){for(var c=0;c<a;c++){var d=z[b+4*c>>2],e=xc[d];e&&(Z.deleteTexture(e),e.name=0,xc[d]=null)}},u:function(a){Z.depthFunc(a)},v:function(a){Z.depthMask(!!a)},d:function(a){Z.disable(a)},H:function(a){Z.disableVertexAttribArray(a)},xa:function(a,b,c){Z.drawArrays(a,b,c)},ya:function(a,b,c,d){Z.drawElements(a,b,c,d)},e:function(a){Z.enable(a)},Aa:function(a){Z.enableVertexAttribArray(a)},I:function(a){Z.frontFace(a)},Ta:function(a,b){Hc(a,b,"createBuffer",uc)},Ra:function(a,
b){Hc(a,b,"createRenderbuffer",wc)},Oa:function(a,b){Hc(a,b,"createTexture",xc)},Ha:function(a,b){return Z.getAttribLocation(W[a],y(b))},f:function(a,b){Ic(a,b)},Ja:function(a,b,c,d){a=Z.getProgramInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&d?u(a,v,d,b):0;c&&(z[c>>2]=b)},U:function(a,b,c){if(c)if(a>=tc)Y(1281);else if(a=W[a],35716==b)a=Z.getProgramInfoLog(a),null===a&&(a="(unknown error)"),z[c>>2]=a.length+1;else if(35719==b){if(!a.oc)for(b=0;b<Z.getProgramParameter(a,35718);++b)a.oc=Math.max(a.oc,
Z.getActiveUniform(a,b).name.length+1);z[c>>2]=a.oc}else if(35722==b){if(!a.mc)for(b=0;b<Z.getProgramParameter(a,35721);++b)a.mc=Math.max(a.mc,Z.getActiveAttrib(a,b).name.length+1);z[c>>2]=a.mc}else if(35381==b){if(!a.nc)for(b=0;b<Z.getProgramParameter(a,35382);++b)a.nc=Math.max(a.nc,Z.getActiveUniformBlockName(a,b).length+1);z[c>>2]=a.nc}else z[c>>2]=Z.getProgramParameter(a,b);else Y(1281)},gb:function(a,b,c,d){a=Z.getShaderInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?u(a,v,d,b):0;c&&(z[c>>
2]=b)},pa:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),z[c>>2]=a?a.length+1:0):35720==b?(a=Z.getShaderSource(X[a]),z[c>>2]=a?a.length+1:0):z[c>>2]=Z.getShaderParameter(X[a],b):Y(1281)},Ua:function(a){var b=zc[a];if(!b){switch(a){case 7939:b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Jc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||Y(1280);b=b&&Jc(b);break;case 7938:b=Jc("OpenGL ES 2.0 ("+
Z.getParameter(7938)+")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Jc(b);break;default:Y(1280)}zc[a]=b}return b},n:function(a,b){b=y(b);if(a=W[a]){var c=a,d=c.kc,e=c.cd,f;if(!d)for(c.kc=d={},c.bd={},f=0;f<Z.getProgramParameter(c,35718);++f){var g=Z.getActiveUniform(c,f);var k=g.name;g=g.size;var p=Kc(k);p=0<p?k.slice(0,p):k;var r=c.Cc;c.Cc+=g;e[p]=[g,r];for(k=
0;k<g;++k)d[r]=k,c.bd[r++]=p}c=a.kc;d=0;e=b;f=Kc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.cd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Z.getUniformLocation(a,b)))return d}else Y(1281);return-1},Ka:function(a){a=W[a];Z.linkProgram(a);a.kc=0;a.cd={}},P:function(a,b){Z.polygonOffset(a,b)},Pa:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},l:function(a,b,c,d){Z.scissor(a,b,c,d)},ib:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=d?z[d+4*f>>2]:-1;e+=y(z[c+4*f>>2],0>g?void 0:g)}Z.shaderSource(X[a],
e)},lb:function(a,b,c){Z.stencilFunc(a,b,c)},O:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},t:function(a){Z.stencilMask(a)},kb:function(a,b,c){Z.stencilOp(a,b,c)},N:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},Ma:function(a,b,c,d,e,f,g,k,p){var r=Z,q=r.texImage2D;if(p){var t=k-5120;t=1==t?v:4==t?z:6==t?A:5==t||28922==t?wa:va;var w=31-Math.clz32(t.BYTES_PER_ELEMENT);p=t.subarray(p>>w,p+e*(d*({5:3,6:4,8:2,29502:3,29504:4}[g-6402]||1)*(1<<w)+4-1&-4)>>w)}else p=null;q.call(r,a,b,c,d,e,f,g,k,p)},
g:function(a,b,c){Z.texParameteri(a,b,c)},G:function(a,b,c){if(288>=b)for(var d=Mc[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);Z.uniform1fv(Lc(a),d)},T:function(a,b){Z.uniform1i(Lc(a),b)},F:function(a,b,c){if(144>=b)for(var d=Mc[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);Z.uniform2fv(Lc(a),d)},E:function(a,b,c){if(96>=b)for(var d=Mc[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=
A.subarray(c>>2,c+12*b>>2);Z.uniform3fv(Lc(a),d)},D:function(a,b,c){if(72>=b){var d=Mc[4*b-1],e=A;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=A.subarray(c>>2,c+16*b>>2);Z.uniform4fv(Lc(a),d)},C:function(a,b,c,d){if(18>=b){var e=Mc[16*b-1],f=A;d>>=2;for(var g=0;g<16*b;g+=16){var k=d+g;e[g]=f[k];e[g+1]=f[k+1];e[g+2]=f[k+2];e[g+3]=f[k+3];e[g+4]=f[k+4];e[g+5]=f[k+5];e[g+6]=f[k+6];e[g+7]=f[k+7];e[g+8]=f[k+8];e[g+9]=f[k+9];e[g+10]=f[k+10];e[g+11]=
f[k+11];e[g+12]=f[k+12];e[g+13]=f[k+13];e[g+14]=f[k+14];e[g+15]=f[k+15]}}else e=A.subarray(d>>2,d+64*b>>2);Z.uniformMatrix4fv(Lc(a),!!c,e)},j:function(a){a=W[a];Z.useProgram(a);Z.fd=a},Ba:function(a,b){Z.vertexAttribDivisor(a,b)},Ca:function(a,b,c,d,e,f){Z.vertexAttribPointer(a,b,c,!!d,e,f)},m:function(a,b,c,d){Z.viewport(a,b,c,d)},$a:function(){h.Vc=function(a){0!=Qc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.Vc)},_a:function(){h.$c=function(a){a=a.clipboardData.getData("text");
ka("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",h.$c)},Za:function(a){h.Vd=[];a=y(a);a=document.getElementById(a);h.Wc=function(b){b.stopPropagation();b.preventDefault()};h.Xc=function(b){b.stopPropagation();b.preventDefault()};h.Yc=function(b){b.stopPropagation();b.preventDefault()};h.Zc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;h.Bc=c;Rc(c.length);var d;for(d=0;d<c.length;d++)ka("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Sc(b.clientX,
b.clientY)};a.addEventListener("dragenter",h.Wc,!1);a.addEventListener("dragleave",h.Xc,!1);a.addEventListener("dragover",h.Yc,!1);a.addEventListener("drop",h.Zc,!1)},r:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Tc()});document.body.append(a)},Y:function(a){return 0>a||a>=h.Bc.length?0:h.Bc[a].size},Va:function(a,b,c,d,e){var f=new FileReader;f.onload=function(g){g=g.target.result;
g.byteLength>d?Uc(a,0,1,b,0,c,d,e):(v.set(new Uint8Array(g),c),Uc(a,1,0,b,g.byteLength,c,d,e))};f.onerror=function(){Uc(a,0,2,b,0,c,d,e)};f.readAsArrayBuffer(h.Bc[a])},q:function(){document.getElementById("_sokol_app_input_element").focus()},qb:function(a){a=y(a);h.jc=document.getElementById(a);h.jc||console.log("sokol_app.h: invalid target:"+a);h.jc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},ta:function(){window.removeEventListener("beforeunload",
h.Vc)},pb:function(){window.removeEventListener("paste",h.$c)},ob:function(a){a=y(a);a=document.getElementById(a);a.removeEventListener("dragenter",h.Wc);a.removeEventListener("dragleave",h.Xc);a.removeEventListener("dragover",h.Yc);a.removeEventListener("drop",h.Zc)},z:function(){h.jc&&h.jc.requestPointerLock&&h.jc.requestPointerLock()},p:function(){document.getElementById("_sokol_app_input_element").blur()},Wa:function(a){a=y(a);var b=document.createElement("textarea");b.setAttribute("autocomplete",
"off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ua:function(){return h.Wb?h.Wb.bufferSize:0},wa:function(a,b,c){h.Nb=null;h.Wb=null;"undefined"!==typeof AudioContext?h.Nb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?
h.Nb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(h.Nb=null,console.log("sokol_audio.h: no WebAudio support"));return h.Nb?(console.log("sokol_audio.h: sample rate ",h.Nb.sampleRate),h.Wb=h.Nb.createScriptProcessor(c,0,b),h.Wb.onaudioprocess=function(d){var e=d.outputBuffer.length,f=Vc(e);if(f)for(var g=d.outputBuffer.numberOfChannels,k=0;k<g;k++)for(var p=d.outputBuffer.getChannelData(k),r=0;r<e;r++)p[r]=A[(f>>2)+(g*r+k)]},h.Wb.connect(h.Nb.destination),a=function(){h.Nb&&"suspended"===
h.Nb.state&&h.Nb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},va:function(){return h.Nb?h.Nb.sampleRate:0},B:function(){null!==h.Nb&&(h.Wb&&h.Wb.disconnect(),h.Nb.close(),h.Nb=null,h.Wb=null)},A:function(){return navigator.userAgent.includes("Macintosh")?1:0},s:function(){return performance.now()}};
(function(){function a(e){h.asm=e.exports;ia=h.asm.rb;ta=e=ia.buffer;h.HEAP8=x=new Int8Array(e);h.HEAP16=ua=new Int16Array(e);h.HEAP32=z=new Int32Array(e);h.HEAPU8=v=new Uint8Array(e);h.HEAPU16=va=new Uint16Array(e);h.HEAPU32=wa=new Uint32Array(e);h.HEAPF32=A=new Float32Array(e);h.HEAPF64=B=new Float64Array(e);xa=h.asm.ub;za.unshift(h.asm.sb);C--;h.monitorRunDependencies&&h.monitorRunDependencies(C);0==C&&(null!==Ea&&(clearInterval(Ea),Ea=null),Fa&&(e=Fa,Fa=null,e()))}function b(e){a(e.instance)}
function c(e){return Ja().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){m("failed to asynchronously prepare wasm: "+f);n(f)})}var d={a:Wc};C++;h.monitorRunDependencies&&h.monitorRunDependencies(C);if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return m("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ha||"function"!==typeof WebAssembly.instantiateStreaming||Ga()||"function"!==typeof fetch?c(b):fetch(D,
{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){m("wasm streaming compile failed: "+f);m("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.sb).apply(null,arguments)};
var F=h._malloc=function(){return(F=h._malloc=h.asm.tb).apply(null,arguments)},Tc=h.__sapp_emsc_notify_keyboard_hidden=function(){return(Tc=h.__sapp_emsc_notify_keyboard_hidden=h.asm.vb).apply(null,arguments)};h.__sapp_emsc_onpaste=function(){return(h.__sapp_emsc_onpaste=h.asm.wb).apply(null,arguments)};
var Qc=h.__sapp_html5_get_ask_leave_site=function(){return(Qc=h.__sapp_html5_get_ask_leave_site=h.asm.xb).apply(null,arguments)},Rc=h.__sapp_emsc_begin_drop=function(){return(Rc=h.__sapp_emsc_begin_drop=h.asm.yb).apply(null,arguments)};h.__sapp_emsc_drop=function(){return(h.__sapp_emsc_drop=h.asm.zb).apply(null,arguments)};
var Sc=h.__sapp_emsc_end_drop=function(){return(Sc=h.__sapp_emsc_end_drop=h.asm.Ab).apply(null,arguments)},Uc=h.__sapp_emsc_invoke_fetch_cb=function(){return(Uc=h.__sapp_emsc_invoke_fetch_cb=h.asm.Bb).apply(null,arguments)};h._main=function(){return(h._main=h.asm.Cb).apply(null,arguments)};
var Vc=h.__saudio_emsc_pull=function(){return(Vc=h.__saudio_emsc_pull=h.asm.Db).apply(null,arguments)},Pc=h.___errno_location=function(){return(Pc=h.___errno_location=h.asm.Eb).apply(null,arguments)},ma=h.stackSave=function(){return(ma=h.stackSave=h.asm.Fb).apply(null,arguments)},na=h.stackRestore=function(){return(na=h.stackRestore=h.asm.Gb).apply(null,arguments)},la=h.stackAlloc=function(){return(la=h.stackAlloc=h.asm.Hb).apply(null,arguments)},Xc;
function Yc(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Fa=function Zc(){Xc||$c();Xc||(Fa=Zc)};
function $c(a){function b(){if(!Xc&&(Xc=!0,h.calledRun=!0,!ja)){h.noFSInit||Lb||(Lb=!0,Kb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Nb("stdin",h.stdin):Fb("/dev/tty","/dev/stdin"),h.stdout?Nb("stdout",null,h.stdout):Fb("/dev/tty","/dev/stdout"),h.stderr?Nb("stderr",null,h.stderr):Fb("/dev/tty1","/dev/stderr"),P("/dev/stdin",0),P("/dev/stdout",1),P("/dev/stderr",1));nb=!1;Pa(za);Pa(Aa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(ad){var c=a,d=h._main;c=c||[];var e=c.length+
1,f=la(4*(e+1));z[f>>2]=sa(da);for(var g=1;g<e;g++)z[(f>>2)+g]=sa(c[g-1]);z[(f>>2)+e]=0;try{var k=d(e,f);if(!noExitRuntime){if(h.onExit)h.onExit(k);ja=!0}ea(k,new Yc(k))}catch(p){p instanceof Yc||"unwind"==p||ea(1,p)}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)c=h.postRun.shift(),Ca.unshift(c);Pa(Ca)}}a=a||ca;if(!(0<C)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Da();Pa(ya);0<C||(h.setStatus?(h.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=$c;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var ad=!0;h.noInitialRun&&(ad=!1);$c();
