#include "IconsForkAwesome.h"
#include "stdlib.h"
#include "localization.h"
#include <string.h>
#include <stdio.h>

//Special thanks to https://github.com/shooterspps for the Chinese Translation
static char* zh_localization_array[]={
    ICON_FK_FILE_O " Load Game", ICON_FK_FILE_O u8" 载入游戏",
    "Up", u8"上",
    "Down", u8"下",
    "Left", u8"左",
    "Right", u8"右",
    "Start", u8"开始",
    "Select", u8"选择",
    "Fold Screen (NDS)", u8"折叠屏幕 (NDS)",
    "Tap Screen (NDS)", u8"点击屏幕 (NDS)",
    "Emulator " ICON_FK_PAUSE "/" ICON_FK_PLAY, u8"模拟器 " ICON_FK_PAUSE "/" ICON_FK_PLAY, 
    "Emulator " ICON_FK_BACKWARD,        u8"模拟器 " ICON_FK_BACKWARD,
    "Emulator " ICON_FK_FORWARD,         u8"模拟器 " ICON_FK_FORWARD,
    "Emulator " ICON_FK_FAST_FORWARD,    u8"模拟器 " ICON_FK_FAST_FORWARD,
    "Capture State 0", u8"即时存档 0",
    "Restore State 0", u8"即时读档 0",
    "Capture State 1", u8"即时存档 1",
    "Restore State 1", u8"即时读档 1",
    "Capture State 2", u8"即时存档 2",
    "Restore State 2", u8"即时读档 2",
    "Capture State 3", u8"即时存档 3",
    "Restore State 3", u8"即时读档 3",
    "Analog Up/Down", u8"摇杆 上/下",
    "Analog Left/Right", u8"摇杆 左/右",
    "Analog L", u8"扳机 L",
    "Analog R", u8"扳机 R",
    "Display FPS: %2.1f\n", u8"显示屏 FPS: %2.1f\n",
    "Emulation FPS: %2.1f\n", u8"模拟器 FPS: %2.1f\n",
    ICON_FK_VOLUME_UP " Audio", ICON_FK_VOLUME_UP u8" 音频",
    "Left Audio Channel", u8"音频左声道",
    "Right Audio Channel", u8"音频右声道",
    "Channel 0", u8"声道 0",
    "Channel 1", u8"声道 1",
    "Channel 2", u8"声道 2",
    "Channel 3", u8"声道 3",
    "Channel 4", u8"声道 4",
    "Channel 5", u8"声道 5",
    "Channel 6", u8"声道 6",
    "Channel 7", u8"声道 7",
    "Channel 8", u8"声道 8",
    "Channel 9", u8"声道 9",
    "Channel A", u8"声道 A",
    "Channel B", u8"声道 B",
    "Channel C", u8"声道 C",
    "Channel D", u8"声道 D",
    "Channel E", u8"声道 E",
    "Channel F", u8"声道 F",
    "Channel 1 (Square)", u8"声道 1 (方形)",
    "Channel 2 (Square)", u8"声道 2 (方形)",
    "Channel 3 (Wave)", u8"声道 3 (波形)",
    "Channel 4 (Noise)", u8"声道 4 (噪声)",
    "Channel A (FIFO)", u8"声道 A (FIFO)",
    "Channel B (FIFO)", u8"声道 B (FIFO)",
    "Audio Ring (Samples Available: %d)", u8"音频环绕 (可用采样: %d)",
    "Audio Watchdog Triggered %d Times", u8"音频定时触发 %d 时间",
    ICON_FK_INFO_CIRCLE " Build Info", ICON_FK_INFO_CIRCLE u8" 构建信息",
    "Commit Hash:", u8"哈希值提交:",
    ICON_FK_SERVER " Registers", ICON_FK_SERVER u8" 寄存器",
    ICON_FK_LIST_OL " Disassembly", ICON_FK_LIST_OL u8" 反汇编",
    ICON_FK_EXCHANGE " Read/Write Memory Address", ICON_FK_EXCHANGE u8" 读/写内存地址",
    "address", u8"地址",
    "data (32 bit)", u8"数据 (32 bit)",
    "data (16 bit)", u8"数据 (16 bit)",
    "data (8 bit)", u8"数据 (8 bit)",
    "data (signed 32b)", u8"数据 (写入 32b)",
    "data (signed 16b)", u8"数据 (写入 16b)",
    "data (signed 8b)", u8"数据 (写入 8b)",
    ICON_FK_PENCIL_SQUARE_O " Memory", ICON_FK_PENCIL_SQUARE_O u8" 内存",
    ICON_FK_AREA_CHART " Emulator Stats", ICON_FK_AREA_CHART u8" 模拟器统计",
    "Show/Hide %s Panel\n", u8"显示/隐藏 %s面板\n",
    "Press new button " ICON_FK_SIGN_IN, u8"按下按键 " ICON_FK_SIGN_IN,
    "Move Axis ", u8"移动轴 ",
    "Not bound", u8"不绑定",
    "Hat %d %s", u8"方向 %d %s",
    "Analog %d %s", u8"手柄轴 %d %s",
    "Key %d", u8"按键 %d",
    "Analog %d (%0.2f)", u8"手柄轴 %d (%0.2f)",
    "Load ROM from file (.gb, .gbc, .gba, .zip)", u8"从文件中载入 ROM (.gb, .gbc, .gba, .zip)",
    "You can also drag & drop a ROM to load it", u8"你也可以通过拖放载入一个 ROM",
    "Load ROM(.gb, .gbc, .gba, .zip), save(.sav), or GBA bios (gba_bios.bin) from file", u8"从文件中载入 ROM(.gb, .gbc, .gba, .zip), save(.sav), 或 GBA bios (gba_bios.bin)",
    "You can also drag & drop a ROM/save file to load it", u8"你也可以通过拖放载入一个 ROM/存档文件",
    "Open ROM", u8"打开 ROM",
    ICON_FK_CLOCK_O " Load Recently Played Game", ICON_FK_CLOCK_O u8" 载入最近玩过的游戏",
    ICON_FK_DOWNLOAD " Export Save", ICON_FK_DOWNLOAD  u8" 导出存档",
    "No recently played games", u8"最近没有玩过游戏",
    ICON_FK_GAMEPAD " Controllers", ICON_FK_GAMEPAD u8" 控制器",
    "Controller", u8"控制器",
    "No Controller", u8"无控制器",
    "Reset Default Controller Bindings", u8"重置控制器默认绑定",
    "Rumble Supported", u8"支持震动",
    "Rumble Not Supported", u8"不支持震动",
    ICON_FK_FLOPPY_O " Save States", ICON_FK_FLOPPY_O u8" 即时存档",
    "Save Slot %d", u8"存档位置 %d",
    "Capture", u8"存档",
    "Restore", u8"读档",
    "This save state came from an incompatible build. SkyEmu has attempted to recover it, but there may be issues", u8"这个即时存档来自一个不兼容的构建. SkyEmu 已经尝试恢复, 但可能会有问题",
    ICON_FK_DESKTOP " Display Settings", ICON_FK_DESKTOP u8" 显示设置",
    "Screen Shader", u8"屏幕着色器",
    "Pixelate\0Bilinear\0LCD\0LCD & Subpixels\0Smooth Upscale (xBRZ)\0", u8"像素化\0双线性\0LCD\0LCD & 子像素\0高级平滑过滤 (xBRZ)\0",
    "Screen Rotation", u8"屏幕旋转",
    "0 degrees\00090 degrees\000180 degrees\000270 degrees\0", u8"0°\00090°\000180°\000270°\0",
    "Color Correction", u8"颜色校正",
    "Strength: %.2f", u8"强度: %.2f",
    "Screen Ghosting", u8"屏幕残影",
    "Force Integer Scaling", u8"强制整数缩放",
    "Stretch Screen to Fit", u8"拉伸适应屏幕",
    "Game Boy Color Palette", u8"Game Boy Color 调色板",
    "GB Palette %d", u8"GB 调色板 %d",
    "Reset Palette to Defaults", u8"重置调色板默认值",
    ICON_FK_KEYBOARD_O " Keybinds", ICON_FK_KEYBOARD_O u8" 键盘快捷键",
    "Reset Default Keybinds", u8"重置键盘快捷键默认值",
    ICON_FK_WRENCH " Advanced",ICON_FK_WRENCH u8" 高级",
    "Light Mode", u8"浅色模式",
    "Show Debug Tools", u8"显示调试工具",
    "Adjust volume", u8"调节音量",
    "Show/Hide Menu Panel", u8"显示/隐藏菜单面板",
    "Rewind at 8x speed", u8"以8倍速度倒带",
    "Rewind at 4x speed", u8"以4倍速度倒带",
    "Toggle pause/play.\n When paused, the rom selection screen will be shown.", u8"切换暂停/游玩.\n 暂停时, 屏幕显示选择 rom 菜单.",
    "Run at 2x Speed", u8"以2倍速度快进",
    "Run at the fastest speed possible", u8"速度无限制快进",
    "Screen", u8"屏幕",
    "LCD Shader Init", u8"LCD 着色器初始化",
    "Menu", u8"菜单",
    "Copy as..", u8"复制..",
    "Current", u8"当前",
    "Original", u8"原始",
    "Opacity", u8"不透明度",
    ICON_FK_HAND_O_RIGHT " Touch Control Settings", ICON_FK_HAND_O_RIGHT u8" 触摸控制设置",
    "Hide when inactive", u8"不活动时隐藏",
    ICON_FK_FILE_O " Dump Memory to File", ICON_FK_FILE_O u8" 转储内存文件",
    "Start Address", u8"起始地址",
    "Size", u8"大小",
    "Save Memory Dump", u8"保存转储内存",
    ICON_FK_RANDOM " Last Branch Locations", ICON_FK_RANDOM u8" 最后分支位置",
    "Opacity: %.2f", u8"不透明度: %.2f",
    "Step Instruction", u8"步进指令",
    "Disconnect Log", u8"断开日志",
    ICON_FK_FOLDER_OPEN " Open File From Disk", ICON_FK_FOLDER_OPEN u8" 从磁盘打开文件",
    "Exit File Browser", u8"退出文件浏览",
    "Go back to recently loaded games", u8"返回最近载入的游戏",
    "Go to parent directory", u8"转到上级目录",
    "UP", u8"上",
    "DOWN", u8"下",
    "LEFT", u8"左",
    "RIGHT", u8"右",
    "Reset Game", u8"重置游戏",
    "Turbo A", u8"连发 A",
    "Turbo B", u8"连发 B",
    "Turbo X", u8"连发 X",
    "Turbo Y", u8"连发 Y",
    "Turbo L", u8"连发 L",
    "Turbo R", u8"连发 R",
    "Solar Sensor+", u8"太阳能传感器+",
    "Solar Sensor-", u8"太阳能传感器-",
    "Theme", u8"主题",
    "Solar Sensor", u8"太阳能传感器",
    "Brightness: %.2f", u8"亮度: %.2f",
    "Dark\0Light\0Black\0", u8"深色\0浅色\0黑色\0",
    "Always Show Menu/Nav Bar", u8"始终显示菜单/导航栏",
    "Language", u8"语言",

    "SPACE", u8"空格",
    "ESCAPE", u8"ESC",
    "ENTER", u8"回车",
    "BACKSPACE", u8"退格键",
    "INSERT", u8"插入",
    "DELETE", u8"删除",
    "RIGHT", u8"右",
    "LEFT", u8"左",
    "DOWN", u8"下",
    "UP", u8"上",
    "LEFT_SHIFT", u8"左 Shift",
    "LEFT_CONTROL", u8"左 Control",
    "LEFT_ALT", u8"左 Alt",
    "LEFT_SUPER", u8"左 Super",
    "RIGHT_SHIFT", u8"右 Shift",
    "RIGHT_CONTROL", u8"右 Control",
    "RIGHT_ALT", u8"右 Alt",
    "RIGHT_SUPER", u8"右 Super",
    "MENU", u8"菜单",
    NULL,NULL
};

const char ** localization_map=NULL;
size_t localization_size=0;
int se_localize_cmp(const void *a, const void*b){return strcmp(((const char**)a)[0],((const char**)b)[0]);}
void se_set_language(int language_enum){
    const char ** new_map = NULL; 
    if(language_enum==SE_LANG_CHINESE)new_map = zh_localization_array; 
    if(new_map!=localization_map){
        localization_map=new_map;
        localization_size=0;
        if(localization_map){
            while(localization_map[localization_size*2])++localization_size;
            qsort(localization_map,localization_size,sizeof(const char*)*2,se_localize_cmp);
        }
    }
}
const char* se_language_string(int language_enum){
    switch (language_enum){
        case SE_LANG_DEFAULT: return se_localize("Default");
        case SE_LANG_ENGLISH: return "English";
        case SE_LANG_CHINESE: return u8"中文";
    }
    return "";
}
const char* se_localize(const char* string){
    if(localization_map==NULL)return string; 
    const char** result = (const char**)bsearch(&string,localization_map,localization_size,sizeof(const char*)*2,se_localize_cmp);
    if(!result)return string;
    else return result[1];
}
